import type { HierarchyGuard } from "@xecms/authorization";
import { AUTHORIZATION_MANAGE_PERMISSION } from "./identifiers.js";
import type { AuthorizationPermissionRecord } from "./types.js";

const PERMISSION_CATALOG_SOURCE = [
  ["authorization.read", "none", true],
  [AUTHORIZATION_MANAGE_PERMISSION, "none", false, true],
  ["content.list", "none", true],
  ["content.read", "none", true],
  ["content.create", "none", true],
  ["content.update", "none", true],
  ["content.delete", "none", true],
  ["content.purge", "none", true],
  ["content.publish", "none", true],
  ["content.unpublish", "none", true],
  ["content.archive", "none", true],
  ["content.restore", "none", true],
  ["content.revision.read", "none", true],
  ["content.revision.restore", "none", true],
  ["schema.read", "none", true],
  ["schema.create", "none", true],
  ["schema.update", "none", true],
  ["schema.delete", "none", true],
  ["schema.apply", "none", true],
  ["schema.rollback", "none", true],
  ["schema.export", "none", true],
  ["identity.read", "none", true],
  ["identity.invite", "none", true],
  ["identity.update", "target-subject", true],
  ["identity.disable", "target-subject", true],
  ["identity.credentials.reset", "target-subject", true],
  ["identity.session.revoke", "target-subject", true],
  ["identity.owner.transfer", "target-subject", false, true],
  // A Content-only Identity has no System Subject yet, so there is no valid
  // System hierarchy target to compare until this operation succeeds.
  ["identity.system-membership.create", "none", true],
  ["service-account.create", "none", true],
  ["service-account.update", "target-subject", true],
  ["group.read", "none", true],
  ["group.create", "none", true],
  ["group.update", "none", true],
  ["group.member.manage", "none", true],
  ["role.read", "none", true],
  ["role.create", "target-role", true],
  ["role.update", "target-role", true],
  ["role.delete", "target-role", true],
  ["role.assign", "target-binding", true],
  ["role.reorder", "target-role", true],
  ["authority-level.read", "none", true],
  ["authority-level.create", "none", true],
  ["authority-level.update", "none", true],
  ["authority-level.delete", "none", true],
  ["media.read", "none", true],
  ["media.upload", "none", true],
  ["media.delete", "none", true],
  ["plugin.read", "none", true],
  ["plugin.install", "none", true],
  ["plugin.configure", "none", true],
  ["plugin.enable", "none", true],
  ["plugin.disable", "none", true],
  ["plugin.uninstall", "none", true],
  ["job.read", "none", true],
  ["job.retry", "none", true],
  ["audit.read", "none", true],
  ["audit.export", "none", true],
  ["retention.read", "none", true],
  ["retention.update", "none", true],
  ["retention.preview", "none", true],
  ["retention.apply", "none", true],
  ["media.consistency.read", "none", true],
  ["api-key.create", "none", true],
  ["api-key.revoke", "none", true],
  ["system.settings.update", "none", true],
  ["system.settings.read", "none", true],
  ["site.read", "none", true],
  ["site.create", "none", true],
  ["site.update", "none", true],
  ["site.archive", "none", true],
  ["site.collection.bind", "none", true],
  ["admin-app.read", "none", true],
  ["admin-app.create", "none", true],
  ["admin-app.update", "none", true],
  ["admin-app.apply", "none", true],
  ["admin-app.delete", "none", true],
  ["admin-app.export", "none", true],
  ["admin-app.access", "none", true],
  ["admin-app.page.read", "none", true],
  ["admin-app.page.unmask", "none", true],
  ["admin-app.action.execute", "none", true],
] as const satisfies readonly (readonly [string, HierarchyGuard, boolean, boolean?])[];

export const DEFAULT_PERMISSION_CATALOG: readonly AuthorizationPermissionRecord[] = Object.freeze(
  PERMISSION_CATALOG_SOURCE.map(([key, hierarchyGuard, delegatable, isProtected]) => Object.freeze({
    key,
    hierarchyGuard,
    delegatable,
    ...(isProtected === undefined ? {} : { protected: isProtected }),
  })),
);

export const CONTENT_PERMISSIONS = Object.freeze([
  "content.list",
  "content.read",
  "content.create",
  "content.update",
  "content.delete",
  "content.purge",
  "content.publish",
  "content.unpublish",
  "content.archive",
  "content.restore",
  "content.revision.read",
  "content.revision.restore",
]);

export const ROLE_MANAGEMENT_PERMISSIONS = Object.freeze([
  "role.read",
  "role.create",
  "role.update",
  "role.delete",
  "role.assign",
  "role.reorder",
]);

export const IDENTITY_PERMISSIONS = Object.freeze([
  "identity.read",
  "identity.invite",
  "identity.update",
  "identity.disable",
  "identity.credentials.reset",
  "identity.session.revoke",
  "identity.system-membership.create",
  "service-account.create",
  "service-account.update",
  "group.read",
  "group.create",
  "group.update",
  "group.member.manage",
]);
