import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toAdminApiError, useAdminApi, type RetentionCounts, type RetentionPlan,
  type UnifiedAuditCategory, type UnifiedAuditQuery, type UnifiedAuditSource } from "@xecms/admin";
import { Badge, Button, Callout, ConfirmDialog, EmptyState, SelectField, TextInput } from "@xecms/ui";
import { Page, PageHeader, SectionHeader } from "../components/page.js";
import { LoadError, PageLoading } from "../components/async-state.js";
import { queryKeys } from "../queries.js";
import styles from "../operations.module.css";

type View = "overview"|"audit"|"retention"|"media";
const countLabels:ReadonlyArray<[keyof RetentionCounts,string]>=[
  ["systemAudit","System audit"],["documentAudit","Document audit"],
  ["authorizationAudit","Authorization audit"],["dispatchedOutbox","Dispatched outbox"],
  ["succeededDeliveries","Succeeded delivery"],["deadDeliveries","Dead delivery"],
  ["expiredSessions","Expired session"],["softDeletedDocuments","Soft-deleted document (report only)"],
];
const message=(error:unknown)=>error===undefined||error===null?null:<Callout tone="error">{toAdminApiError(error).message}</Callout>;
const days=(value:string)=>value.trim()===""?null:Number(value);

export function OperationsPage(){
  const api=useAdminApi(),client=useQueryClient();
  const [view,setView]=useState<View>("overview");
  const [category,setCategory]=useState(""),[source,setSource]=useState(""),[action,setAction]=useState(""),[actorId,setActorId]=useState(""),[targetId,setTargetId]=useState("");
  const [query,setQuery]=useState<UnifiedAuditQuery>({limit:50});
  const auditKey=JSON.stringify(query);
  const audit=useQuery({queryKey:queryKeys.audit(auditKey),queryFn:()=>api.operations.listAudit(query)});
  const policy=useQuery({queryKey:queryKeys.retentionPolicy,queryFn:()=>api.operations.getRetentionPolicy()});
  const extensions=useQuery({queryKey:queryKeys.pluginExtensions,queryFn:()=>api.plugins.extensions()});
  const [editOpen,setEditOpen]=useState(false),[password,setPassword]=useState("");
  const [auditDays,setAuditDays]=useState(""),[outboxDays,setOutboxDays]=useState("30"),[successDays,setSuccessDays]=useState("30"),[deadDays,setDeadDays]=useState(""),[sessionDays,setSessionDays]=useState("7"),[documentDays,setDocumentDays]=useState("");
  const [plan,setPlan]=useState<RetentionPlan|null>(null),[applyOpen,setApplyOpen]=useState(false);
  const [exportFrom,setExportFrom]=useState(()=>new Date(Date.now()-7*86_400_000).toISOString()),[exportTo,setExportTo]=useState(()=>new Date().toISOString());
  const update=useMutation({mutationFn:()=>api.operations.updateRetentionPolicy({expectedRevision:policy.data!.revision,auditDays:days(auditDays),dispatchedOutboxDays:days(outboxDays),succeededDeliveryDays:days(successDays),deadDeliveryDays:days(deadDays),expiredSessionDays:days(sessionDays),softDeletedDocumentDays:days(documentDays),currentPassword:password}),onSuccess:async()=>{setEditOpen(false);setPassword("");setPlan(null);await client.invalidateQueries({queryKey:queryKeys.retentionPolicy});}});
  const preview=useMutation({mutationFn:()=>api.operations.previewRetention(policy.data!.revision),onSuccess:setPlan});
  const apply=useMutation({mutationFn:()=>api.operations.applyRetention(plan!.id,{expectedPolicyRevision:policy.data!.revision,currentPassword:password}),onSuccess:async(value)=>{setPlan(value);setApplyOpen(false);setPassword("");await Promise.all([client.invalidateQueries({queryKey:["operations","audit"]}),client.invalidateQueries({queryKey:queryKeys.retentionPolicy})]);}});
  const media=useMutation({mutationFn:()=>api.operations.checkMediaConsistency()});
  const exporting=useMutation({mutationFn:()=>api.operations.exportAudit({...withoutCursor(query),from:exportFrom,to:exportTo}),onSuccess:(text)=>download(text)});
  const recent=useMemo(()=>audit.data?.items??[],[audit.data]);
  const failed=recent.filter(entry=>entry.outcome==="failed"||entry.outcome==="denied").length;
  const dead=recent.filter(entry=>entry.source==="delivery").length;
  const runSearch=()=>setQuery({limit:50,...(category===""?{}:{category:category as UnifiedAuditCategory}),...(source===""?{}:{source:source as UnifiedAuditSource}),...(action.trim()===""?{}:{action:action.trim()}),...(actorId.trim()===""?{}:{actorId:actorId.trim()}),...(targetId.trim()===""?{}:{targetId:targetId.trim()})});
  const openEdit=()=>{const value=policy.data!;setAuditDays(value.auditDays?.toString()??"");setOutboxDays(value.dispatchedOutboxDays?.toString()??"");setSuccessDays(value.succeededDeliveryDays?.toString()??"");setDeadDays(value.deadDeliveryDays?.toString()??"");setSessionDays(value.expiredSessionDays?.toString()??"");setDocumentDays(value.softDeletedDocumentDays?.toString()??"");setPassword("");setEditOpen(true)};
  if(audit.isPending||policy.isPending)return <Page><PageLoading label="운영 데이터를 불러오는 중"/></Page>;
  if(audit.isError||policy.isError)return <Page><LoadError error={audit.error??policy.error}/></Page>;
  const tabs:ReadonlyArray<[View,string]>=[["overview","Overview"],["audit","통합 감사"],["retention","보존 정책"],["media","Media consistency"]];
  return <Page><PageHeader eyebrow="Operations" title="운영 및 감사" description="보안·콘텐츠·권한·Worker 이벤트를 한 시간축에서 확인하고 운영 데이터를 안전하게 정리합니다."/>
    <nav className={styles.tabs} aria-label="운영 화면"><>{tabs.map(([id,label])=><Button key={id} size="small" variant={view===id?"secondary":"quiet"} onPress={()=>setView(id)}>{label}</Button>)}</></nav>
    {view==="overview"?<>
      <div className={styles.metricGrid}><Metric label="최근 조회 이벤트" value={recent.length} hint="현재 감사 페이지"/><Metric label="실패·거부" value={failed} hint="보안과 작업 실패" tone={failed>0?"warning":"normal"}/><Metric label="Dead delivery" value={dead} hint="Worker 확인 필요" tone={dead>0?"warning":"normal"}/><Metric label="Retention revision" value={`r${policy.data!.revision}`} hint={policy.data!.auditDays===null?"Audit 영구 보존":`Audit ${policy.data!.auditDays}일`}/></div>
      {extensions.data?.filter(card=>card.slot==="operations.overview").map(card=><section className={styles.panel} key={card.id}><SectionHeader title={card.title} description={`${card.pluginName} · ${card.description}`}/><div className={styles.actions}>{card.status?<Badge tone="success">{card.status}</Badge>:null}{card.link?<a href={card.link.href}>{card.link.label}</a>:null}</div></section>)}
      <section className={styles.panel}><SectionHeader title="최근 운영 이벤트" description="모든 원본 source를 정규화하고 민감값을 마스킹한 결과입니다."/><AuditTable items={recent.slice(0,8)}/><div className={styles.actions}><Button variant="secondary" onPress={()=>setView("audit")}>전체 감사 열기</Button><Button variant="secondary" onPress={()=>setView("retention")}>보존 정책 확인</Button></div></section>
    </>:null}
    {view==="audit"?<>
      <section className={styles.panel}><SectionHeader title="Audit filter" description="Category, source, actor와 target을 함께 좁힐 수 있습니다."/><div className={styles.filterGrid}><SelectField label="Category" value={category} onChange={setCategory} options={[{value:"",label:"전체"},...(["security","identity","content","schema","authorization","settings","site","worker","media","retention","plugin"] as const).map(value=>({value,label:value}))]}/><SelectField label="Source" value={source} onChange={setSource} options={[{value:"",label:"전체"},...(["system","document","authorization","delivery"] as const).map(value=>({value,label:value}))]}/><TextInput label="Action" value={action} onChange={setAction}/><TextInput label="Actor ID" value={actorId} onChange={setActorId}/><TextInput label="Target ID" value={targetId} onChange={setTargetId}/></div><div className={styles.actions}><Button onPress={runSearch}>필터 적용</Button><Button variant="quiet" onPress={()=>{setCategory("");setSource("");setAction("");setActorId("");setTargetId("");setQuery({limit:50})}}>초기화</Button></div></section>
      <section className={styles.panel}><SectionHeader title="통합 감사 로그" description={`${recent.length}개 · cursor 기반 페이지`}/>{recent.length===0?<EmptyState title="감사 이벤트가 없습니다" description="현재 필터에 해당하는 이벤트가 없습니다."/>:<AuditTable items={recent}/>}<div className={styles.actions}>{audit.data!.nextCursor?<Button variant="secondary" onPress={()=>setQuery({...withoutCursor(query),cursor:audit.data!.nextCursor,limit:50})}>다음 페이지</Button>:null}<Button variant="quiet" onPress={()=>setQuery(withoutCursor(query))}>첫 페이지</Button></div></section>
      <section className={styles.panel}><SectionHeader title="NDJSON export" description="최대 90일, 50,000건이며 화면과 같은 redaction을 적용합니다."/><div className={styles.filterGrid}><TextInput label="From (ISO 8601)" value={exportFrom} onChange={setExportFrom}/><TextInput label="To (ISO 8601)" value={exportTo} onChange={setExportTo}/></div><div className={styles.actions}><Button onPress={()=>exporting.mutate()} isDisabled={exporting.isPending}>{exporting.isPending?"생성 중…":"NDJSON 내보내기"}</Button></div>{message(exporting.error)}</section>
    </>:null}
    {view==="retention"?<>
      <section className={styles.panel}><SectionHeader title="Workspace retention policy" description={`Revision ${policy.data!.revision} · ${new Date(policy.data!.updatedAt).toLocaleString("ko-KR")}`}/><PolicyGrid policy={policy.data!}/><Callout tone="warning"><strong>문서와 미디어는 자동 삭제하지 않습니다.</strong> Soft-deleted document는 preview에 후보로만 보고됩니다.</Callout><div className={styles.actions}><Button variant="secondary" onPress={openEdit}>정책 변경</Button><Button onPress={()=>preview.mutate()} isDisabled={preview.isPending}>{preview.isPending?"계산 중…":"정리 미리보기"}</Button></div>{message(preview.error)}</section>
      {plan?<section className={styles.panel}><SectionHeader title="Retention plan" description={`${plan.id} · ${plan.status} · ${new Date(plan.expiresAt).toLocaleString("ko-KR")} 만료`}/><CountTable counts={plan.counts} bytes={plan.estimatedBytes}/>{plan.status==="previewed"?<><Callout tone="warning">Apply 직전에 대상 수와 policy revision을 다시 검증하며, 달라졌다면 아무것도 삭제하지 않습니다.</Callout><div className={styles.actions}><Button variant="danger" onPress={()=>{setPassword("");setApplyOpen(true)}}>이 plan 적용</Button></div></>:<Callout tone="success">정리가 원자적으로 완료되었습니다.</Callout>}</section>:null}
    </>:null}
    {view==="media"?<section className={styles.panel}><SectionHeader title="Media consistency" description="DB metadata와 local storage file을 비교하며 자동 삭제는 수행하지 않습니다."/><div className={styles.actions}><Button onPress={()=>media.mutate()} isDisabled={media.isPending}>{media.isPending?"검사 중…":"Consistency 검사"}</Button></div>{message(media.error)}{media.data?<div className={styles.metricGrid}><Metric label="정상 파일" value={media.data.healthyCount}/><Metric label="누락 파일" value={media.data.missing.length} tone={media.data.missing.length?"warning":"normal"}/><Metric label="Orphan storage" value={media.data.orphanStorageKeys.length} tone={media.data.orphanStorageKeys.length?"warning":"normal"}/><Metric label="미완료 upload" value={media.data.incomplete.length} tone={media.data.incomplete.length?"warning":"normal"}/></div>:<EmptyState title="아직 검사하지 않았습니다" description="읽기 전용 consistency report를 실행해 보세요."/>}</section>:null}
    {editOpen?<ConfirmDialog title="보존 정책 변경" confirmLabel="정책 저장" isPending={update.isPending} isConfirmDisabled={!password} onCancel={()=>setEditOpen(false)} onConfirm={()=>update.mutate()}><div className={styles.dialogGrid}><RetentionInput label="Audit (최소 90일)" value={auditDays} onChange={setAuditDays}/><RetentionInput label="Dispatched outbox (최소 7일)" value={outboxDays} onChange={setOutboxDays}/><RetentionInput label="Succeeded delivery (최소 7일)" value={successDays} onChange={setSuccessDays}/><RetentionInput label="Dead delivery (최소 30일)" value={deadDays} onChange={setDeadDays}/><RetentionInput label="Expired session (최소 1일)" value={sessionDays} onChange={setSessionDays}/><RetentionInput label="Soft-delete report (최소 1일)" value={documentDays} onChange={setDocumentDays}/><TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/><p className={styles.hint}>빈 값은 영구 보존입니다.</p>{message(update.error)}</div></ConfirmDialog>:null}
    {applyOpen&&plan?<ConfirmDialog title="Retention plan 적용" confirmLabel="검증 후 정리" danger isPending={apply.isPending} isConfirmDisabled={!password} onCancel={()=>setApplyOpen(false)} onConfirm={()=>apply.mutate()}><div className={styles.dialogGrid}><p>미리보기의 안전한 운영 데이터만 정리합니다. 처리 중 작업과 문서·미디어는 삭제되지 않습니다.</p><TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/>{message(apply.error)}</div></ConfirmDialog>:null}
  </Page>;
}

function Metric({label,value,hint,tone="normal"}:{label:string;value:string|number;hint?:string;tone?:"normal"|"warning"}){return <article className={`${styles.metric} ${tone==="warning"?styles.warning:""}`}><span>{label}</span><strong>{value}</strong>{hint?<small>{hint}</small>:null}</article>}
function AuditTable({items}:{items:readonly import("@xecms/admin").UnifiedAuditRecord[]}){return <div className={styles.tableWrap}><table><thead><tr><th>시각</th><th>분류</th><th>Action / target</th><th>Actor</th><th>결과</th></tr></thead><tbody>{items.map(entry=><tr key={entry.id}><td>{new Date(entry.occurredAt).toLocaleString("ko-KR")}</td><td><Badge>{entry.category}</Badge><span className={styles.source}>{entry.source}</span></td><td><details><summary><strong>{entry.action}</strong><span>{entry.targetType} · {entry.targetId??"—"}</span></summary><pre>{JSON.stringify({before:entry.before,after:entry.after,metadata:entry.metadata},null,2)}</pre></details></td><td>{entry.actorLabel??entry.actorIdentityId??entry.actorSubjectId??"system"}</td><td><Badge tone={entry.outcome==="succeeded"?"success":entry.outcome==="informational"?"neutral":"warning"}>{entry.outcome}</Badge></td></tr>)}</tbody></table></div>}
function PolicyGrid({policy}:{policy:import("@xecms/admin").RetentionPolicy}){const entries:[[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null],[string,number|null]]=[["Audit",policy.auditDays],["Dispatched outbox",policy.dispatchedOutboxDays],["Succeeded delivery",policy.succeededDeliveryDays],["Dead delivery",policy.deadDeliveryDays],["Expired session",policy.expiredSessionDays],["Soft-delete report",policy.softDeletedDocumentDays]];return <div className={styles.policyGrid}>{entries.map(([label,value])=><div key={label}><span>{label}</span><strong>{value===null?"영구 보존":`${value}일`}</strong></div>)}</div>}
function CountTable({counts,bytes}:{counts:RetentionCounts;bytes:Readonly<Record<string,number>>}){return <div className={styles.tableWrap}><table><thead><tr><th>대상</th><th>건수</th><th>예상 bytes</th></tr></thead><tbody>{countLabels.map(([key,label])=><tr key={key}><td>{label}</td><td><strong>{counts[key].toLocaleString()}</strong></td><td>{(bytes[key]??0).toLocaleString()}</td></tr>)}</tbody></table></div>}
function RetentionInput({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <TextInput label={label} type="number" value={value} onChange={onChange}/>}
function withoutCursor(query:UnifiedAuditQuery):UnifiedAuditQuery{const {cursor:_cursor,...rest}=query;return rest}
function download(text:string){const blob=new Blob([text],{type:"application/x-ndjson;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`xecms-audit-${new Date().toISOString().slice(0,10)}.ndjson`;anchor.click();URL.revokeObjectURL(url)}
