import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { toAdminApiError,useAdminApi,type PluginAction,type PluginCatalogItem,type PluginDataAction,type PluginPlan } from "@xecms/admin";
import { Badge,Button,Callout,ConfirmDialog,EmptyState,SelectField,TextInput } from "@xecms/ui";
import { LoadError,PageLoading } from "../components/async-state.js";
import { Page,PageHeader,SectionHeader } from "../components/page.js";
import { queryKeys } from "../queries.js";
import styles from "../plugins.module.css";

const error=(value:unknown)=>value?<Callout tone="error">{toAdminApiError(value).message}</Callout>:null;
export function PluginsPage(){const api=useAdminApi(),qc=useQueryClient(),catalog=useQuery({queryKey:queryKeys.plugins,queryFn:()=>api.plugins.catalog()});const[plan,setPlan]=useState<PluginPlan|null>(null),[selected,setSelected]=useState<PluginCatalogItem|null>(null),[dataAction,setDataAction]=useState<PluginDataAction|"">(""),[password,setPassword]=useState(""),[applyOpen,setApplyOpen]=useState(false),[configOpen,setConfigOpen]=useState(false),[config,setConfig]=useState("{}");
  const preview=useMutation({mutationFn:({plugin,action}:{plugin:PluginCatalogItem;action:PluginAction})=>api.plugins.preview({pluginId:plugin.pluginId,action,...(action==="uninstall"&&dataAction?{dataAction}:{}),expectedPluginRevision:plugin.installed?.revision??null}),onSuccess:value=>setPlan(value)});
  const apply=useMutation({mutationFn:()=>api.plugins.apply(plan!.id,{pluginId:plan!.pluginId,expectedPluginRevision:plan!.expectedPluginRevision,currentPassword:password}),onSuccess:async value=>{setPlan(value);setApplyOpen(false);setPassword("");await qc.invalidateQueries({queryKey:queryKeys.plugins})}});
  const update=useMutation({mutationFn:()=>api.plugins.updateConfig(selected!.pluginId,{expectedRevision:selected!.installed!.revision,config:JSON.parse(config) as Record<string,unknown>,currentPassword:password}),onSuccess:async()=>{setConfigOpen(false);setPassword("");await qc.invalidateQueries({queryKey:queryKeys.plugins})}});
  if(catalog.isPending)return <Page><PageLoading label="Plugin catalog를 불러오는 중"/></Page>;if(catalog.isError)return <Page><LoadError error={catalog.error}/></Page>;const items=catalog.data.items;
  const action=(plugin:PluginCatalogItem):PluginAction=>plugin.installed===null?"install":plugin.installed.desiredState==="enabled"?"disable":plugin.installed.desiredState==="disabled"?"uninstall":"enable";
  const runPreview=(plugin:PluginCatalogItem)=>{setSelected(plugin);setPlan(null);setDataAction("");preview.mutate({plugin,action:action(plugin)})};
  return <Page><PageHeader eyebrow="Trusted extensions" title="Plugins" description="배포에 포함된 trusted npm Plugin을 검증된 manifest와 durable lifecycle plan으로 관리합니다."/>
    <Callout tone="warning"><strong>Plugin 코드는 서버와 같은 권한으로 실행됩니다.</strong> 상태 변경과 설정은 적용 후 서버 재시작이 필요하며, 요청 중 package를 다운로드하지 않습니다.</Callout>
    {items.length===0?<EmptyState title="허용된 Plugin이 없습니다" description="서버 deployment의 trusted catalog에 package를 추가하세요."/>:<div className={styles.grid}>{items.map(plugin=><article className={styles.card} key={plugin.pluginId}><div className={styles.cardTop}><div><span className={styles.package}>{plugin.packageName}</span><h2>{plugin.displayName}</h2><p>{plugin.description??"설명이 없습니다."}</p></div><div className={styles.badges}><Badge tone={plugin.runtimeLoaded?"success":"neutral"}>{plugin.runtimeLoaded?"Loaded":"Not loaded"}</Badge><Badge tone={plugin.installed?.desiredState==="enabled"?"info":"neutral"}>{plugin.installed?.desiredState??"Catalog"}</Badge></div></div><dl><div><dt>Version</dt><dd>{plugin.version}</dd></div><div><dt>Core range</dt><dd>{String((plugin.manifest["compatibility"] as Record<string,unknown>|undefined)?.["core"]??"—")}</dd></div><div><dt>Migrations</dt><dd>{Array.isArray(plugin.manifest["migrations"])?plugin.manifest["migrations"].length:0}</dd></div><div><dt>Restart</dt><dd>{plugin.restartRequired?"Required":"Reconciled"}</dd></div></dl>{plugin.restartRequired?<Callout tone="warning">현재 process와 desired state가 다릅니다. 서버를 재시작하세요.</Callout>:null}<div className={styles.actions}><Button onPress={()=>runPreview(plugin)} isDisabled={preview.isPending}>{label(action(plugin))} 미리보기</Button>{plugin.installed?<Button variant="secondary" onPress={()=>{setSelected(plugin);setConfig(JSON.stringify(plugin.installed!.config,null,2));setPassword("");setConfigOpen(true)}}>설정</Button>:null}<Button variant="quiet" onPress={()=>setSelected(selected?.pluginId===plugin.pluginId?null:plugin)}>Manifest</Button></div>{selected?.pluginId===plugin.pluginId&&!configOpen?<details open className={styles.manifest}><summary>Manifest</summary><pre>{JSON.stringify(plugin.manifest,null,2)}</pre></details>:null}</article>)}</div>}
    {selected&&action(selected)==="uninstall"?<section className={styles.panel}><SectionHeader title="Uninstall data policy" description="데이터가 있으면 preserve, export 또는 purge를 명시해야 합니다."/><SelectField label="잔존 데이터" value={dataAction} onChange={value=>setDataAction(value as PluginDataAction|"")} options={[{value:"",label:"선택하지 않음"},{value:"preserve",label:"Preserve — table 유지"},{value:"export",label:"Export — JSON 보관 후 제거"},{value:"purge",label:"Purge — 영구 제거"}]}/><div className={styles.actions}><Button onPress={()=>preview.mutate({plugin:selected,action:"uninstall"})}>선택으로 다시 계산</Button></div></section>:null}
    {plan?<section className={styles.panel}><SectionHeader title={`${label(plan.action)} plan`} description={`${plan.id} · ${new Date(plan.expiresAt).toLocaleString("ko-KR")} 만료`}/><div className={styles.planGrid}><div><span>Dependencies</span><strong>{plan.dependencyIds.length}</strong></div><div><span>Migrations</span><strong>{plan.migrationIds.length}</strong></div><div><span>Schema refs</span><strong>{plan.schemaReferences.length}</strong></div><div><span>Data rows</span><strong>{Object.values(plan.dataCounts).reduce((sum,value)=>sum+value,0)}</strong></div></div>{plan.blockers.length?<div className={styles.blockers}>{plan.blockers.map((blocker,index)=><Callout tone="error" key={`${blocker.code}-${index}`}><strong>{blocker.code}</strong> — {blocker.message}</Callout>)}</div>:plan.status==="applied"?<Callout tone="success">Lifecycle apply가 완료되었습니다. 재시작 후 runtime 상태가 맞춰집니다.</Callout>:<Callout tone="warning">Apply 시 manifest, revision, dependency와 data count를 다시 계산합니다.</Callout>}<div className={styles.actions}>{plan.status==="previewed"?<Button variant={plan.action==="uninstall"?"danger":"primary"} isDisabled={plan.blockers.length>0} onPress={()=>{setPassword("");setApplyOpen(true)}}>이 plan 적용</Button>:null}{plan.exportId?<Button variant="secondary" onPress={()=>void api.plugins.getExport(plan.exportId!)}>Export 확인</Button>:null}</div>{error(preview.error)}</section>:null}
    {applyOpen&&plan?<ConfirmDialog title={`${label(plan.action)} 적용`} confirmLabel="재인증 후 적용" danger={plan.action==="uninstall"} isPending={apply.isPending} isConfirmDisabled={!password} onCancel={()=>setApplyOpen(false)} onConfirm={()=>apply.mutate()}><div className={styles.dialog}><p>Migration과 Plugin 상태는 하나의 transaction으로 적용됩니다.</p><TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/>{error(apply.error)}</div></ConfirmDialog>:null}
    {configOpen&&selected?.installed?<ConfirmDialog title={`${selected.displayName} 설정`} confirmLabel="설정 저장" isPending={update.isPending} isConfirmDisabled={!password} onCancel={()=>setConfigOpen(false)} onConfirm={()=>update.mutate()}><div className={styles.dialog}><label className={styles.jsonLabel}>JSON config<textarea value={config} onChange={event=>setConfig(event.target.value)} rows={8}/></label><TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/>{error(update.error)}</div></ConfirmDialog>:null}
  </Page>}
function label(action:PluginAction){return action==="install"?"Install":action==="enable"?"Enable":action==="disable"?"Disable":"Uninstall"}
