import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toAdminApiError, useAdminApi, type Site } from "@xecms/admin";
import { Badge, Button, Callout, ConfirmDialog, EmptyState, SelectField, TextInput } from "@xecms/ui";
import { Icon } from "../components/icon.js";
import { Page, PageHeader, SectionHeader } from "../components/page.js";
import {
  DisplayModeGate,
  DisplayModeSelector,
  displayModeAtLeast,
  useDisplayMode,
} from "../display-mode.js";
import { LoadError, PageLoading } from "../components/async-state.js";
import { queryKeys } from "../queries.js";
import styles from "../identity-realms.module.css";

const error = (value:unknown) => value===null||value===undefined?null:<Callout tone="error">{toAdminApiError(value).message}</Callout>;
export function SettingsPage(){
  const api=useAdminApi(),qc=useQueryClient();
  const {mode}=useDisplayMode();
  const diagnostics=useQuery({queryKey:queryKeys.diagnostics,queryFn:()=>api.settings.diagnostics()});
  const workspace=useQuery({queryKey:queryKeys.workspaceSettings,queryFn:()=>api.settings.getWorkspace()});
  const sites=useQuery({queryKey:queryKeys.sites,queryFn:()=>api.sites.list()});
  const collections=useQuery({queryKey:queryKeys.collections,queryFn:()=>api.collections.list()});
  const policy=useQuery({queryKey:queryKeys.authorization,queryFn:()=>api.authorization.getPolicy()});
  const [workspaceOpen,setWorkspaceOpen]=useState(false),[displayName,setDisplayName]=useState(""),[timezone,setTimezone]=useState("Asia/Seoul"),[locale,setLocale]=useState("ko-KR"),[password,setPassword]=useState("");
  const [createOpen,setCreateOpen]=useState(false),[siteKey,setSiteKey]=useState(""),[siteName,setSiteName]=useState(""),[siteUrl,setSiteUrl]=useState("");
  const [editSite,setEditSite]=useState<Site|null>(null),[editName,setEditName]=useState(""),[editUrl,setEditUrl]=useState("");
  const [danger,setDanger]=useState<{site:Site;kind:"archive"|"reactivate"|"default"}|null>(null),[replacement,setReplacement]=useState("");
  const [scopeSite,setScopeSite]=useState(""),[scopeCollection,setScopeCollection]=useState(""),[scopePassword,setScopePassword]=useState("");
  const refresh=async()=>{await qc.invalidateQueries({queryKey:["settings"]});};
  const updateWorkspace=useMutation({mutationFn:()=>api.settings.updateWorkspace({expectedRevision:workspace.data!.revision,displayName,defaultTimezone:timezone,adminLocale:locale,currentPassword:password}),onSuccess:async()=>{setWorkspaceOpen(false);setPassword("");await refresh();}});
  const createSite=useMutation({mutationFn:()=>api.sites.create({key:siteKey,name:siteName,...(siteUrl.trim()===""?{}:{canonicalUrl:siteUrl})}),onSuccess:async()=>{setCreateOpen(false);setSiteKey("");setSiteName("");setSiteUrl("");await refresh();}});
  const updateSite=useMutation({mutationFn:()=>api.sites.update(editSite!.siteId,{expectedRevision:editSite!.revision,name:editName,...(editUrl.trim()===""?{}:{canonicalUrl:editUrl})}),onSuccess:async()=>{setEditSite(null);await refresh();}});
  const lifecycle=useMutation({mutationFn:async()=>{const d=danger!;if(d.kind==="default")return api.sites.setDefault(d.site.siteId,{expectedRevision:d.site.revision,currentPassword:password});if(d.kind==="archive")return api.sites.archive(d.site.siteId,{expectedRevision:d.site.revision,currentPassword:password,...(replacement===""?{}:{replacementDefaultSiteId:replacement})});return api.sites.reactivate(d.site.siteId,{expectedRevision:d.site.revision,currentPassword:password});},onSuccess:async()=>{setDanger(null);setPassword("");setReplacement("");await refresh();}});
  const selected=sites.data?.items.find(s=>s.siteId===scopeSite),bound=selected?.collectionIds.includes(scopeCollection)??false;
  const binding=useMutation({mutationFn:()=>{const input={expectedSiteRevision:selected!.revision,expectedPolicyRevision:policy.data!.revision,currentPassword:scopePassword};return bound?api.sites.unbindCollection(selected!.siteId,scopeCollection,input):api.sites.bindCollection(selected!.siteId,scopeCollection,input);},onSuccess:async()=>{setScopePassword("");await Promise.all([refresh(),qc.invalidateQueries({queryKey:queryKeys.authorization})]);}});
  if(diagnostics.isPending||workspace.isPending||sites.isPending)return <Page><PageLoading label="설정을 불러오는 중"/></Page>;
  if(diagnostics.isError||workspace.isError||sites.isError)return <Page><LoadError error={diagnostics.error??workspace.error??sites.error}/></Page>;
  const d=diagnostics.data!,w=workspace.data!,items=sites.data!.items;
  return <Page><PageHeader eyebrow="System settings" title="설정 및 사이트" description="환경 진단과 Workspace·Site 권한 경계를 관리합니다." actions={displayModeAtLeast(mode,"standard")?<Button onPress={()=>{setSiteName("");setCreateOpen(true)}}><Icon name="plus" size={16}/>Site 생성</Button>:undefined}/>
    <section className={styles.panel}><SectionHeader title="Admin 표시 모드" description="권한은 바뀌지 않으며 메뉴와 기술 정보의 표시량만 조절합니다."/><DisplayModeSelector/></section>
    <DisplayModeGate minimum="standard"><div className={styles.summaryGrid}><div><span>XeCMS</span><strong>{d.xecmsVersion}</strong></div><div><span>환경</span><strong>{d.environment}</strong></div><div><span>Node.js</span><strong>{d.nodeVersion}</strong></div><div><span>PostgreSQL</span><strong>{d.postgresVersion}</strong></div><div><span>Schema mode</span><strong>{d.schemaMode}</strong></div><div><span>Worker</span><strong>{d.workerEnabled?"활성":"비활성"}</strong></div><div><span>Upload limit</span><strong>{Math.round(d.uploadLimitBytes/1024/1024)} MB</strong></div></div></DisplayModeGate>
    {d.schemaMode!=="editable"?<Callout tone="warning"><strong>Schema {d.schemaMode}</strong> — 서버 환경 정책으로 Schema editor mutation이 제한됩니다.</Callout>:null}
    <section className={styles.panel}><SectionHeader title="Workspace" description={`Revision ${w.revision} · ${w.updatedAt}`}/><div className={styles.summaryGrid}><div><span>표시 이름</span><strong>{w.displayName}</strong></div><div><span>기본 timezone</span><strong>{w.defaultTimezone}</strong></div><div><span>Admin locale</span><strong>{w.adminLocale}</strong></div><div><span>Storage</span><strong>{d.storageAdapter}</strong></div></div><div className={styles.formActions}><Button variant="secondary" onPress={()=>{setDisplayName(w.displayName);setTimezone(w.defaultTimezone);setLocale(w.adminLocale);setWorkspaceOpen(true)}}>Workspace 설정 변경</Button></div></section>
    <DisplayModeGate minimum="standard"><section className={styles.panel}><SectionHeader title="Sites" description="첫 Site는 자동으로 default가 되며 archived Site의 콘텐츠 쓰기는 차단됩니다."/>{items.length===0?<EmptyState title="Site가 없습니다" description="첫 Site를 생성하면 default Site로 지정됩니다."/>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Site</th><th>URL</th><th>상태</th><th>Collections</th><th>작업</th></tr></thead><tbody>{items.map(s=><tr key={s.siteId}><td><strong>{s.name}</strong><span className={styles.secondaryLine}>{s.key}</span></td><td>{s.canonicalUrl??"—"}</td><td>{s.isDefault?<Badge tone="info">Default</Badge>:<Badge tone={s.status==="active"?"success":"neutral"}>{s.status}</Badge>}</td><td>{s.collectionIds.length}</td><td><div className={styles.formActions}><Button size="small" variant="quiet" onPress={()=>{setEditSite(s);setEditName(s.name);setEditUrl(s.canonicalUrl??"")}}>수정</Button>{!s.isDefault&&s.status==="active"?<Button size="small" variant="quiet" onPress={()=>setDanger({site:s,kind:"default"})}>Default 지정</Button>:null}<Button size="small" variant={s.status==="active"?"danger":"secondary"} onPress={()=>setDanger({site:s,kind:s.status==="active"?"archive":"reactivate"})}>{s.status==="active"?"Archive":"Reactivate"}</Button></div></td></tr>)}</tbody></table></div>}{error(createSite.error??updateSite.error??lifecycle.error)}</section></DisplayModeGate>
    <DisplayModeGate minimum="advanced">{items.length>0?<section className={styles.panel}><SectionHeader title="Collection Site scope" description="Binding은 권한 Resource의 parent를 Site 아래로 원자 이동합니다."/><div className={styles.fieldGrid}><SelectField label="Site" value={scopeSite} onChange={setScopeSite} options={[{value:"",label:"선택"},...items.filter(s=>s.status==="active").map(s=>({value:s.siteId,label:s.name}))]}/><SelectField label="Collection" value={scopeCollection} onChange={setScopeCollection} options={[{value:"",label:"선택"},...(collections.data?.items??[]).map(c=>({value:c.id,label:c.label??c.name}))]}/><TextInput label="현재 비밀번호" type="password" value={scopePassword} onChange={setScopePassword}/></div><div className={styles.formActions}><Button onPress={()=>binding.mutate()} isDisabled={!selected||!scopeCollection||!scopePassword||!policy.data}>{bound?"Binding 해제":"Site에 Binding"}</Button></div>{error(binding.error)}</section>:null}</DisplayModeGate>
    {workspaceOpen?<ConfirmDialog title="Workspace 설정 변경" confirmLabel="설정 저장" isPending={updateWorkspace.isPending} isConfirmDisabled={!displayName||!timezone||!locale||!password} onCancel={()=>setWorkspaceOpen(false)} onConfirm={()=>updateWorkspace.mutate()}><div className={styles.dialogStack}><TextInput label="표시 이름" value={displayName} onChange={setDisplayName}/><TextInput label="기본 timezone" value={timezone} onChange={setTimezone}/><TextInput label="Admin locale" value={locale} onChange={setLocale}/><TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/>{error(updateWorkspace.error)}</div></ConfirmDialog>:null}
    {createOpen?<ConfirmDialog title="Site 생성" confirmLabel="생성" isPending={createSite.isPending} isConfirmDisabled={!siteKey||!siteName} onCancel={()=>setCreateOpen(false)} onConfirm={()=>createSite.mutate()}><div className={styles.dialogStack}><TextInput label="Site key" value={siteKey} onChange={setSiteKey}/><TextInput label="Site 이름" value={siteName} onChange={setSiteName}/><TextInput label="Canonical URL" value={siteUrl} onChange={setSiteUrl}/></div></ConfirmDialog>:null}
    {editSite?<ConfirmDialog title="Site 수정" confirmLabel="저장" isPending={updateSite.isPending} onCancel={()=>setEditSite(null)} onConfirm={()=>updateSite.mutate()}><div className={styles.dialogStack}><TextInput label="Site 이름" value={editName} onChange={setEditName}/><TextInput label="Canonical URL" value={editUrl} onChange={setEditUrl}/></div></ConfirmDialog>:null}
    {danger?<ConfirmDialog title={danger.kind==="archive"?"Site Archive":danger.kind==="reactivate"?"Site Reactivate":"Default Site 변경"} confirmLabel="확인" danger={danger.kind==="archive"} isPending={lifecycle.isPending} isConfirmDisabled={!password||(danger.kind==="archive"&&danger.site.isDefault&&!replacement)} onCancel={()=>setDanger(null)} onConfirm={()=>lifecycle.mutate()}><div className={styles.dialogStack}><p><strong>{danger.site.name}</strong>의 상태를 변경합니다.</p>{danger.kind==="archive"&&danger.site.isDefault?<SelectField label="대체 Default Site" value={replacement} onChange={setReplacement} options={[{value:"",label:"선택"},...items.filter(s=>s.siteId!==danger.site.siteId&&s.status==="active").map(s=>({value:s.siteId,label:s.name}))]}/>:null}<TextInput label="현재 비밀번호" type="password" value={password} onChange={setPassword}/>{error(lifecycle.error)}</div></ConfirmDialog>:null}
  </Page>;
}
