import { normalizeSchema } from "./normalize.js";
import type {
  ComponentDefinition,
  FieldDefinition,
  SchemaIrV1,
} from "./types.js";

/**
 * Generates a dependency-light TypeScript contract from canonical Schema IR.
 * No timestamps, revisions, filesystem paths, or iteration over unordered
 * objects are included, so equal manifests produce byte-identical output.
 */
export function generateTypeScriptTypes(manifest: SchemaIrV1): string {
  const schema = normalizeSchema(manifest);
  const components = new Map(
    (schema.components ?? []).map((component) => [component.id, component]),
  );
  const lines: string[] = [
    "/* This file is generated by XeCMS. Do not edit manually. */",
    "export type SchemaJsonPrimitive = null | boolean | number | string;",
    "export type SchemaJsonValue = SchemaJsonPrimitive | readonly SchemaJsonValue[] | { readonly [key: string]: SchemaJsonValue };",
    "export type RichTextDocumentV2 = Readonly<{ format: \"xecms.rich-text\"; formatVersion: 2; content: readonly { readonly [key: string]: SchemaJsonValue }[] }>;",
    "",
  ];

  for (const component of schema.components ?? []) {
    lines.push(renderContainer(componentTypeName(component.name), component.fields, components));
    lines.push("");
  }

  for (const collection of schema.collections) {
    lines.push(renderContainer(documentTypeName(collection.name), collection.fields, components));
    lines.push("");
  }

  lines.push("export interface XeCmsDocumentsByCollectionName {");
  for (const collection of schema.collections) {
    lines.push(`  readonly ${quote(collection.name)}: ${documentTypeName(collection.name)};`);
  }
  lines.push("}", "");

  lines.push("export interface XeCmsDocumentsByCollectionId {");
  for (const collection of schema.collections) {
    lines.push(`  readonly ${quote(collection.id)}: ${documentTypeName(collection.name)};`);
  }
  lines.push("}", "");

  lines.push(
    "export type XeCmsCollectionName = keyof XeCmsDocumentsByCollectionName;",
    `export type XeCmsRepeatableCollectionName = ${nameUnion(
      schema.collections.filter(({ kind }) => kind !== "singleton").map(({ name }) => name),
    )};`,
    `export type XeCmsSingletonName = ${nameUnion(
      schema.collections.filter(({ kind }) => kind === "singleton").map(({ name }) => name),
    )};`,
  );

  return `${lines.join("\n")}\n`;
}

function renderContainer(
  typeName: string,
  fields: readonly FieldDefinition[],
  components: ReadonlyMap<string, ComponentDefinition>,
): string {
  const lines = [`export interface ${typeName} {`];
  for (const field of fields) {
    lines.push(renderProperty(field, components, 1));
  }
  lines.push("}");
  return lines.join("\n");
}

function renderProperty(
  field: FieldDefinition,
  components: ReadonlyMap<string, ComponentDefinition>,
  indent: number,
): string {
  const prefix = `${"  ".repeat(indent)}readonly ${quote(field.name)}${
    field.required === true ? "" : "?"
  }: `;
  const value = renderFieldType(field, components, indent);
  return `${prefix}${value};`;
}

function renderFieldType(
  field: FieldDefinition,
  components: ReadonlyMap<string, ComponentDefinition>,
  indent: number,
): string {
  switch (field.type) {
    case "text":
    case "textarea":
    case "date":
    case "datetime":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "SchemaJsonValue";
    case "select":
    case "enum": {
      const union = field.options.map(({ value }) => quote(value)).join(" | ");
      return field.multiple === true ? `readonly (${union})[]` : union;
    }
    case "relation":
      return field.cardinality === "many" ? "readonly string[]" : "string";
    case "upload":
      return field.multiple === true ? "readonly string[]" : "string";
    case "object":
      return renderInlineObject(field.fields, components, indent);
    case "array":
      return `readonly (${renderInlineObject(field.fields, components, indent)})[]`;
    case "component": {
      const component = requireComponent(components, field.componentId);
      const reference = componentTypeName(component.name);
      return field.repeatable === true ? `readonly ${reference}[]` : reference;
    }
    case "blocks": {
      const variants = field.allowedComponentIds.map((componentId) => {
        const component = requireComponent(components, componentId);
        return `{ readonly componentId: ${quote(component.id)}; readonly data: ${componentTypeName(
          component.name,
        )} }`;
      });
      return variants.length === 0 ? "readonly never[]" : `readonly (${variants.join(" | ")})[]`;
    }
    case "rich-text":
      return "RichTextDocumentV2";
  }
}

function renderInlineObject(
  fields: readonly FieldDefinition[],
  components: ReadonlyMap<string, ComponentDefinition>,
  indent: number,
): string {
  if (fields.length === 0) return "Readonly<Record<string, never>>";
  const lines = ["{"];
  for (const field of fields) {
    lines.push(renderProperty(field, components, indent + 1));
  }
  lines.push(`${"  ".repeat(indent)}}`);
  return lines.join("\n");
}

function requireComponent(
  components: ReadonlyMap<string, ComponentDefinition>,
  componentId: string,
): ComponentDefinition {
  const component = components.get(componentId);
  if (component === undefined) {
    // normalizeSchema validates references first; this is a defensive guard for
    // callers using a structurally incompatible runtime object.
    throw new TypeError(`Unknown component '${componentId}'.`);
  }
  return component;
}

function documentTypeName(name: string): string {
  return `${upperFirst(name)}Document`;
}

function componentTypeName(name: string): string {
  return `${upperFirst(name)}Component`;
}

function upperFirst(value: string): string {
  return `${value[0]!.toUpperCase()}${value.slice(1)}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function nameUnion(names: readonly string[]): string {
  return names.length === 0 ? "never" : names.map(quote).join(" | ");
}
