import { randomUUID } from "node:crypto";
import { PostgresDatabase,quoteIdentifier } from "@xecms/database";
import type { LightMyRequestResponse } from "fastify";
import { describe,expect,it } from "vitest";
import { loadServerConfig } from "./config.js";
import { buildServer,type XeCmsServer } from "./server.js";

const RUN=process.env["XECMS_RUN_POSTGRES_TESTS"]==="true",DATABASE_URL=process.env["XECMS_TEST_DATABASE_URL"]??process.env["DATABASE_URL"]??"postgresql://xecms:xecms@127.0.0.1:55432/xecms_e2e",ORIGIN="http://127.0.0.1:3200";
interface Session{readonly cookie:string;readonly csrfToken:string}
describe.runIf(RUN)("M4-C4 Plugin HTTP and restart acceptance",()=>{
  it("installs and enables trusted catalog Plugin, then loads Route/Admin slot only after restart",async()=>{const schema=`xecms_m4c4_${randomUUID().replaceAll("-","_")}`,database=new PostgresDatabase({connectionString:DATABASE_URL,schema,maxConnections:5}),config=loadServerConfig({NODE_ENV:"development",DATABASE_URL,XECMS_DB_SCHEMA:schema,XECMS_SESSION_SECRET:"m4c4-plugin-integration-secret-0123456789",XECMS_DEV_SEED:"true",XECMS_DEV_ADMIN_USERNAME:"admin",XECMS_DEV_ADMIN_PASSWORD:"admin",XECMS_ADMIN_ORIGINS:ORIGIN,XECMS_ADMIN_DIST:"/not-used"});let server:XeCmsServer|undefined;try{
    server=await buildServer({database,config,logger:false});let session=await login(server);
    const catalog=await get(server,session,"/api/plugins/catalog");expect(catalog.statusCode,catalog.body).toBe(200);expect(catalog.json().items).toEqual([expect.objectContaining({pluginId:"example-greeter",installed:null,runtimeLoaded:false})]);
    const installPreview=await mutate(server,session,"POST","/api/plugins/plans",{pluginId:"example-greeter",action:"install",expectedPluginRevision:null});expect(installPreview.statusCode,installPreview.body).toBe(201);expect(installPreview.json().blockers).toEqual([]);
    const wrong=await mutate(server,session,"POST",`/api/plugins/plans/${installPreview.json().id}/apply`,{pluginId:"example-greeter",expectedPluginRevision:null,currentPassword:"wrong"});expect(wrong.statusCode).toBe(401);
    const installed=await mutate(server,session,"POST",`/api/plugins/plans/${installPreview.json().id}/apply`,{pluginId:"example-greeter",expectedPluginRevision:null,currentPassword:"admin"});expect(installed.statusCode,installed.body).toBe(200);expect(installed.json().result).toMatchObject({desiredState:"installed",revision:1});
    const enablePreview=await mutate(server,session,"POST","/api/plugins/plans",{pluginId:"example-greeter",action:"enable",expectedPluginRevision:1});const enabled=await mutate(server,session,"POST",`/api/plugins/plans/${enablePreview.json().id}/apply`,{pluginId:"example-greeter",expectedPluginRevision:1,currentPassword:"admin"});expect(enabled.statusCode,enabled.body).toBe(200);expect(enabled.json().result).toMatchObject({desiredState:"enabled",restartRequired:true});
    expect((await get(server,session,"/api/plugins/example-greeter/hello")).statusCode).toBe(404);expect((await get(server,session,"/api/admin/extensions")).json().cards).toEqual([]);
    await server.close();server=await buildServer({database,config,logger:false});session=await login(server);
    const hello=await get(server,session,"/api/plugins/example-greeter/hello");expect(hello.statusCode,hello.body).toBe(200);expect(hello.json()).toEqual({plugin:"example-greeter",message:"Hello from Example Greeter"});const extensions=await get(server,session,"/api/admin/extensions");expect(extensions.json().cards).toEqual([expect.objectContaining({pluginId:"example-greeter",slot:"operations.overview",status:"Loaded"})]);expect((await get(server,session,"/api/plugins/catalog")).json().items[0]).toMatchObject({runtimeLoaded:true,restartRequired:false});
    const configured=await mutate(server,session,"PATCH","/api/plugins/example-greeter/config",{expectedRevision:2,config:{greeting:"Restarted greeting"},currentPassword:"admin"});expect(configured.statusCode,configured.body).toBe(200);expect(configured.json()).toMatchObject({revision:3,restartRequired:true});expect((await get(server,session,"/api/plugins/example-greeter/hello")).json().message).toBe("Hello from Example Greeter");
    await server.close();server=await buildServer({database,config,logger:false});session=await login(server);expect((await get(server,session,"/api/plugins/example-greeter/hello")).json().message).toBe("Restarted greeting");
    const disablePreview=await mutate(server,session,"POST","/api/plugins/plans",{pluginId:"example-greeter",action:"disable",expectedPluginRevision:3});const disabled=await mutate(server,session,"POST",`/api/plugins/plans/${disablePreview.json().id}/apply`,{pluginId:"example-greeter",expectedPluginRevision:3,currentPassword:"admin"});expect(disabled.json().result).toMatchObject({desiredState:"disabled",revision:4});
    await server.close();server=await buildServer({database,config,logger:false});session=await login(server);expect((await get(server,session,"/api/plugins/example-greeter/hello")).statusCode).toBe(404);expect((await get(server,session,"/api/admin/extensions")).json().cards).toEqual([]);
  }finally{await server?.close();await database.pool.query(`DROP SCHEMA IF EXISTS ${quoteIdentifier(schema)} CASCADE`).catch(()=>undefined);await database.close()}},40_000);
});
async function login(server:XeCmsServer):Promise<Session>{const response=await server.app.inject({method:"POST",url:"/api/auth/login",headers:{origin:ORIGIN},payload:{username:"admin",password:"admin"}});expect(response.statusCode,response.body).toBe(200);return{cookie:String(response.headers["set-cookie"]).split(";",1)[0]!,csrfToken:response.json().csrfToken as string}}
function get(server:XeCmsServer,session:Session,url:string):Promise<LightMyRequestResponse>{return server.app.inject({method:"GET",url,headers:{cookie:session.cookie,origin:ORIGIN}})}
function mutate(server:XeCmsServer,session:Session,method:"POST"|"PATCH",url:string,payload:Readonly<Record<string,unknown>>){return server.app.inject({method,url,headers:{cookie:session.cookie,"x-csrf-token":session.csrfToken,origin:ORIGIN},payload})}
