import { ApplicationError,SYSTEM_WORKSPACE_RESOURCE_ID,type ActorContext,type AuthorizationApplicationService,type PluginPlanAction,type PluginService } from "@xecms/application";
import type { AdminPluginExtensionListDto,ApplyPluginPlanRequest,PluginCatalogListDto,PluginExportDto,PluginListDto,PluginPlanDto,PluginRecordDto,PreviewPluginPlanRequest,UpdatePluginConfigRequest } from "@xecms/contracts";
import type { PluginAdminCard,PluginRoute,XeCmsPluginModule } from "@xecms/plugin-sdk";
import type { FastifyInstance,FastifyRequest } from "fastify";

interface Options{readonly app:FastifyInstance;readonly plugins:PluginService;readonly authorization:AuthorizationApplicationService;readonly requireActor:(request:FastifyRequest,csrf:boolean)=>Promise<ActorContext>;readonly reauthenticate:(request:FastifyRequest,actor:ActorContext,password:string)=>Promise<void>;readonly loadedModules:readonly XeCmsPluginModule[];readonly loadedConfigs:ReadonlyMap<string,Readonly<Record<string,unknown>>>}
export function registerPluginRoutes(options:Options):void{
  const allow=async(actor:ActorContext,permission:string)=>options.authorization.require({realmId:actor.realmId!,subjectId:actor.subjectId},{action:permission,resourceId:SYSTEM_WORKSPACE_RESOURCE_ID});
  const actor=async(request:FastifyRequest,csrf:boolean)=>{const value=await options.requireActor(request,csrf);if(csrf&&value.authentication!=="session")throw new ApplicationError("API_KEY_ADMINISTRATION_FORBIDDEN",403,"API keys cannot change Plugin lifecycle.");return value};
  options.app.get("/api/plugins/catalog",async(request):Promise<PluginCatalogListDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return{items:(await options.plugins.listCatalog(a.workspaceId)).map(catalogDto)}});
  options.app.get("/api/plugins",async(request):Promise<PluginListDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return{items:(await options.plugins.list(a.workspaceId)).map(pluginDto)}});
  options.app.get("/api/plugins/:pluginId",async(request):Promise<PluginRecordDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return pluginDto(await options.plugins.get(a.workspaceId,path(request.params,"pluginId")))});
  options.app.patch("/api/plugins/:pluginId/config",async(request):Promise<PluginRecordDto>=>{const a=await actor(request,true);await allow(a,"plugin.configure");const body=configBody(request.body);await options.reauthenticate(request,a,body.currentPassword);return pluginDto(await options.plugins.updateConfig({workspaceId:a.workspaceId,pluginId:path(request.params,"pluginId"),expectedRevision:body.expectedRevision,config:body.config,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId}))});
  options.app.post("/api/plugins/plans",async(request,reply):Promise<PluginPlanDto>=>{const a=await actor(request,true);const body=previewBody(request.body);await allow(a,permission(body.action));const plan=await options.plugins.preview({workspaceId:a.workspaceId,...body,actorIdentityId:a.identityId!});reply.code(201);return planDto(plan)});
  options.app.get("/api/plugins/plans/:planId",async(request):Promise<PluginPlanDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return planDto(await options.plugins.getPlan(a.workspaceId,path(request.params,"planId")))});
  options.app.post("/api/plugins/plans/:planId/apply",async(request):Promise<PluginPlanDto>=>{const a=await actor(request,true);const body=applyBody(request.body);const plan=await options.plugins.getPlan(a.workspaceId,path(request.params,"planId"));if(plan.pluginId!==body.pluginId)bad("Plugin does not match plan.");await allow(a,permission(plan.action));await options.reauthenticate(request,a,body.currentPassword);return planDto(await options.plugins.apply({workspaceId:a.workspaceId,planId:plan.id,pluginId:body.pluginId,expectedPluginRevision:body.expectedPluginRevision,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId}))});
  options.app.get("/api/plugins/exports/:exportId",async(request):Promise<PluginExportDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return options.plugins.getExport(a.workspaceId,path(request.params,"exportId"))});
  options.app.get("/api/admin/extensions",async(request):Promise<AdminPluginExtensionListDto>=>{const a=await actor(request,false);await allow(a,"plugin.read");return{cards:options.loadedModules.flatMap(module=>(module.admin?.cards??[]).map(card=>cardDto(module,card)))}});
  for(const module of options.loadedModules)for(const route of module.server?.routes??[])registerRuntimeRoute(options,route,module);
}
function registerRuntimeRoute(options:Options,route:PluginRoute,module:XeCmsPluginModule){options.app.route({method:route.method,url:route.path,handler:async(request)=>{const mutation=route.method!=="GET";const actor=await options.requireActor(request,mutation);if(mutation&&actor.authentication!=="session")throw new ApplicationError("API_KEY_PLUGIN_MUTATION_FORBIDDEN",403,"API keys cannot call mutating Plugin routes.");await options.authorization.require({realmId:actor.realmId!,subjectId:actor.subjectId},{action:route.permission,resourceId:SYSTEM_WORKSPACE_RESOURCE_ID});return route.handle({workspaceId:actor.workspaceId,subjectId:actor.subjectId,...(actor.identityId?{identityId:actor.identityId}:{}),params:stringRecord(request.params),query:stringRecord(request.query),body:request.body,config:options.loadedConfigs.get(module.manifest.id)??{}})}})}
function permission(action:PluginPlanAction){return action==="install"?"plugin.install":action==="enable"?"plugin.enable":action==="disable"?"plugin.disable":"plugin.uninstall"}
function previewBody(value:unknown):PreviewPluginPlanRequest{const body=obj(value);exact(body,["pluginId","action","dataAction","expectedPluginRevision"]);const action=enumeration(body["action"],["install","enable","disable","uninstall"] as const,"action");const dataAction=body["dataAction"]===undefined?undefined:enumeration(body["dataAction"],["preserve","export","purge"] as const,"dataAction");const revision=nullableRevision(body["expectedPluginRevision"]);return{pluginId:str(body["pluginId"],"pluginId"),action,...(dataAction?{dataAction}:{}),expectedPluginRevision:revision}}
function applyBody(value:unknown):ApplyPluginPlanRequest{const body=obj(value);exact(body,["pluginId","expectedPluginRevision","currentPassword"]);return{pluginId:str(body["pluginId"],"pluginId"),expectedPluginRevision:nullableRevision(body["expectedPluginRevision"]),currentPassword:str(body["currentPassword"],"currentPassword",1000)}}
function configBody(value:unknown):UpdatePluginConfigRequest{const body=obj(value);exact(body,["expectedRevision","config","currentPassword"]);const config=obj(body["config"]);return{expectedRevision:revision(body["expectedRevision"]),config,currentPassword:str(body["currentPassword"],"currentPassword",1000)}}
function pluginDto(value:import("@xecms/application").PluginRecord):PluginRecordDto{return{...value,manifest:value.manifest as unknown as Readonly<Record<string,unknown>>}}
function catalogDto(value:import("@xecms/application").PluginCatalogRecord){return{...value,manifest:value.manifest as unknown as Readonly<Record<string,unknown>>,installed:value.installed?pluginDto(value.installed):null}}
function planDto(value:import("@xecms/application").PluginPlan):PluginPlanDto{const{result,...rest}=value;return{...rest,...(result===undefined?{}:{result:result?pluginDto(result):null})}}
function cardDto(module:XeCmsPluginModule,card:PluginAdminCard){return{pluginId:module.manifest.id,pluginName:module.manifest.displayName,...card}}
function obj(value:unknown):Record<string,unknown>{if(typeof value!=="object"||value===null||Array.isArray(value))bad("Request object is invalid.");return value as Record<string,unknown>}
function exact(value:Record<string,unknown>,keys:readonly string[]){if(Object.keys(value).some(key=>!keys.includes(key)))bad("Request contains unknown fields.")}
function str(value:unknown,name:string,max=300){if(typeof value!=="string"||value.length<1||value.length>max)bad(`${name} is invalid.`);return value}
function path(value:unknown,key:string){return str(obj(value)[key],key)}
function revision(value:unknown){if(!Number.isSafeInteger(value)||Number(value)<1)bad("revision is invalid.");return Number(value)}
function nullableRevision(value:unknown){return value===null?null:revision(value)}
function enumeration<T extends string>(value:unknown,values:readonly T[],name:string):T{if(typeof value!=="string"||!values.includes(value as T))bad(`${name} is invalid.`);return value as T}
function stringRecord(value:unknown):Record<string,string>{if(typeof value!=="object"||value===null||Array.isArray(value))return{};const output:Record<string,string>={};for(const[key,member]of Object.entries(value))if(typeof member==="string")output[key]=member;return output}
function bad(message:string):never{throw new ApplicationError("PLUGIN_REQUEST_INVALID",400,message)}
