import { ApplicationError, SYSTEM_WORKSPACE_RESOURCE_ID, type ActorContext,
  type AuthorizationApplicationService, type SiteRecord, type SiteService } from "@xecms/application";
import type { CreateSiteRequest, SetDefaultSiteRequest, SiteCollectionBindingRequest, SiteDto,
  SiteListDto, SiteStatusRequest, UpdateSiteRequest } from "@xecms/contracts";
import type { FastifyInstance, FastifyRequest } from "fastify";

export function registerSiteRoutes(options:{readonly app:FastifyInstance;readonly sites:SiteService;
  readonly authorization:AuthorizationApplicationService;readonly requireActor:(request:FastifyRequest,csrf:boolean)=>Promise<ActorContext>;
  readonly reauthenticate:(request:FastifyRequest,actor:ActorContext,password:string)=>Promise<void>}):void{
  const actor=async(request:FastifyRequest,csrf:boolean)=>{const value=await options.requireActor(request,csrf);if(value.authentication!=="session"&&csrf)throw new ApplicationError("API_KEY_ADMINISTRATION_FORBIDDEN",403,"API keys cannot perform protected Site mutations.");return value;};
  const allow=async(value:ActorContext,action:string)=>options.authorization.require({realmId:value.realmId!,subjectId:value.subjectId},{action,resourceId:SYSTEM_WORKSPACE_RESOURCE_ID});
  options.app.get("/api/sites",async(request):Promise<SiteListDto>=>{const a=await actor(request,false);await allow(a,"site.read");return{items:(await options.sites.list(a.workspaceId)).map(dto)};});
  options.app.get("/api/sites/:siteId",async(request):Promise<SiteDto>=>{const a=await actor(request,false);await allow(a,"site.read");return dto(await options.sites.get(path(request.params,"siteId"),a.workspaceId));});
  options.app.post("/api/sites",async(request,reply):Promise<SiteDto>=>{const a=await actor(request,true);await allow(a,"site.create");const b=createBody(request.body);const site=await options.sites.create({workspaceId:a.workspaceId,...b,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId});reply.code(201);return dto(site);});
  options.app.patch("/api/sites/:siteId",async(request):Promise<SiteDto>=>{const a=await actor(request,true);await allow(a,"site.update");const b=updateBody(request.body);return dto(await options.sites.update({siteId:path(request.params,"siteId"),workspaceId:a.workspaceId,...b,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId}));});
  for(const archived of [true,false] as const)options.app.post(`/api/sites/:siteId/${archived?"archive":"reactivate"}`,async(request):Promise<SiteDto>=>{const a=await actor(request,true);await allow(a,"site.archive");const b=statusBody(request.body);await options.reauthenticate(request,a,b.currentPassword);return dto(await options.sites.setArchived({siteId:path(request.params,"siteId"),workspaceId:a.workspaceId,expectedRevision:b.expectedRevision,archived,...(b.replacementDefaultSiteId===undefined?{}:{replacementDefaultSiteId:b.replacementDefaultSiteId}),actorIdentityId:a.identityId!,actorSubjectId:a.subjectId}));});
  options.app.post("/api/sites/:siteId/default",async(request):Promise<SiteDto>=>{const a=await actor(request,true);await allow(a,"site.update");const b=defaultBody(request.body);await options.reauthenticate(request,a,b.currentPassword);return dto(await options.sites.setDefault({siteId:path(request.params,"siteId"),workspaceId:a.workspaceId,expectedRevision:b.expectedRevision,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId}));});
  for(const remove of [false,true] as const)options.app.route({method:remove?"DELETE":"PUT",url:"/api/sites/:siteId/collections/:collectionId",handler:async(request):Promise<SiteDto>=>{const a=await actor(request,true);await allow(a,"site.collection.bind");const b=bindingBody(request.body);await options.reauthenticate(request,a,b.currentPassword);const input={siteId:path(request.params,"siteId"),collectionId:path(request.params,"collectionId"),workspaceId:a.workspaceId,expectedSiteRevision:b.expectedSiteRevision,expectedPolicyRevision:b.expectedPolicyRevision,actorIdentityId:a.identityId!,actorSubjectId:a.subjectId};return dto(await(remove?options.sites.unbindCollection(input):options.sites.bindCollection(input)));}});
}
function dto(s:SiteRecord):SiteDto{return{siteId:s.id,workspaceId:s.workspaceId,key:s.key,name:s.name,...(s.canonicalUrl===undefined?{}:{canonicalUrl:s.canonicalUrl}),status:s.status,isDefault:s.isDefault,revision:s.revision,createdAt:s.createdAt,createdBy:s.createdBy,updatedAt:s.updatedAt,updatedBy:s.updatedBy,...(s.archivedAt===undefined?{}:{archivedAt:s.archivedAt}),collectionIds:s.collectionIds};}
function obj(v:unknown){if(typeof v!=="object"||v===null||Array.isArray(v))bad();return v as Record<string,unknown>;}
function str(v:unknown,n:string){if(typeof v!=="string"||v.length===0||v.length>500)throw new ApplicationError("SITE_REQUEST_INVALID",400,`${n} is invalid.`);return v;}
function rev(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<1)bad();return Number(v);}
function exact(v:Record<string,unknown>,keys:string[]){if(Object.keys(v).some(k=>!keys.includes(k)))bad();}
function path(v:unknown,n:string){return str(obj(v)[n],n);}
function createBody(v:unknown):CreateSiteRequest{const b=obj(v);exact(b,["key","name","canonicalUrl"]);return{key:str(b["key"],"key"),name:str(b["name"],"name"),...(b["canonicalUrl"]===undefined?{}:{canonicalUrl:str(b["canonicalUrl"],"canonicalUrl")})};}
function updateBody(v:unknown):UpdateSiteRequest{const b=obj(v);exact(b,["expectedRevision","name","canonicalUrl"]);return{expectedRevision:rev(b["expectedRevision"]),name:str(b["name"],"name"),...(b["canonicalUrl"]===undefined?{}:{canonicalUrl:str(b["canonicalUrl"],"canonicalUrl")})};}
function statusBody(v:unknown):SiteStatusRequest{const b=obj(v);exact(b,["expectedRevision","currentPassword","replacementDefaultSiteId"]);return{expectedRevision:rev(b["expectedRevision"]),currentPassword:str(b["currentPassword"],"currentPassword"),...(b["replacementDefaultSiteId"]===undefined?{}:{replacementDefaultSiteId:str(b["replacementDefaultSiteId"],"replacementDefaultSiteId")})};}
function defaultBody(v:unknown):SetDefaultSiteRequest{const b=obj(v);exact(b,["expectedRevision","currentPassword"]);return{expectedRevision:rev(b["expectedRevision"]),currentPassword:str(b["currentPassword"],"currentPassword")};}
function bindingBody(v:unknown):SiteCollectionBindingRequest{const b=obj(v);exact(b,["expectedSiteRevision","expectedPolicyRevision","currentPassword"]);return{expectedSiteRevision:rev(b["expectedSiteRevision"]),expectedPolicyRevision:rev(b["expectedPolicyRevision"]),currentPassword:str(b["currentPassword"],"currentPassword")};}
function bad():never{throw new ApplicationError("SITE_REQUEST_INVALID",400,"The Site request is invalid.");}
