/* This file is generated by XeCMS. Do not edit manually. */
export type SchemaJsonPrimitive = null | boolean | number | string;
export type SchemaJsonValue = SchemaJsonPrimitive | readonly SchemaJsonValue[] | { readonly [key: string]: SchemaJsonValue };
export type RichTextDocumentV1 = Readonly<{ format: "xecms.rich-text"; formatVersion: 1; content: readonly { readonly [key: string]: SchemaJsonValue }[] }>;

export interface SeoMetadataComponent {
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "noIndex"?: boolean;
}

export interface HeroBlockComponent {
  readonly "heading": string;
  readonly "eyebrow"?: string;
}

export interface CalloutBlockComponent {
  readonly "tone": "info" | "warning";
  readonly "body": string;
}

export interface SiteSettingsDocument {
  readonly "siteName": string;
  readonly "description"?: string;
  readonly "launchDate"?: string;
  readonly "theme": "system" | "light" | "dark";
  readonly "logo"?: string;
  readonly "seo"?: SeoMetadataComponent;
  readonly "socialLinks"?: readonly ({
    readonly "label": string;
    readonly "url": string;
  })[];
}

export interface AuthorsDocument {
  readonly "name": string;
  readonly "bio"?: string;
  readonly "avatar"?: string;
  readonly "roles"?: readonly ("writer" | "editor" | "photographer")[];
  readonly "profile"?: {
    readonly "location"?: string;
    readonly "website"?: string;
  };
  readonly "metadata"?: SchemaJsonValue;
}

export interface CategoriesDocument {
  readonly "title": string;
  readonly "slug": string;
  readonly "summary"?: string;
}

export interface PostsDocument {
  readonly "title": string;
  readonly "slug": string;
  readonly "excerpt"?: string;
  readonly "body": RichTextDocumentV1;
  readonly "status": "draft" | "review" | "ready";
  readonly "kind": "article" | "news" | "tutorial";
  readonly "featured"?: boolean;
  readonly "publishedAt"?: string;
  readonly "eventDate"?: string;
  readonly "readingMinutes"?: number;
  readonly "tags"?: readonly ("xecms" | "typescript" | "operations")[];
  readonly "author": string;
  readonly "category"?: string;
  readonly "relatedPosts"?: readonly string[];
  readonly "cover"?: string;
  readonly "gallery"?: readonly string[];
  readonly "seo"?: SeoMetadataComponent;
  readonly "sections"?: readonly ({
    readonly "heading": string;
    readonly "body": string;
  })[];
  readonly "layout"?: {
    readonly "width"?: "narrow" | "normal" | "wide";
    readonly "showTableOfContents"?: boolean;
  };
  readonly "contentBlocks"?: readonly ({ readonly componentId: "cmp_blog_hero"; readonly data: HeroBlockComponent } | { readonly componentId: "cmp_blog_callout"; readonly data: CalloutBlockComponent })[];
  readonly "metadata"?: SchemaJsonValue;
}

export interface PagesDocument {
  readonly "title": string;
  readonly "slug": string;
  readonly "body": RichTextDocumentV1;
  readonly "seo"?: SeoMetadataComponent;
}

export interface CommentsDocument {
  readonly "name": string;
  readonly "message": string;
  readonly "post": string;
}

export interface XeCmsDocumentsByCollectionName {
  readonly "siteSettings": SiteSettingsDocument;
  readonly "authors": AuthorsDocument;
  readonly "categories": CategoriesDocument;
  readonly "posts": PostsDocument;
  readonly "pages": PagesDocument;
  readonly "comments": CommentsDocument;
}

export interface XeCmsDocumentsByCollectionId {
  readonly "col_blog_site": SiteSettingsDocument;
  readonly "col_blog_authors": AuthorsDocument;
  readonly "col_blog_categories": CategoriesDocument;
  readonly "col_blog_posts": PostsDocument;
  readonly "col_blog_pages": PagesDocument;
  readonly "col_blog_comments": CommentsDocument;
}

export type XeCmsCollectionName = keyof XeCmsDocumentsByCollectionName;
export type XeCmsRepeatableCollectionName = "authors" | "categories" | "posts" | "pages" | "comments";
export type XeCmsSingletonName = "siteSettings";
