export const queryKeys = {
    bootstrap: ["bootstrap"],
    session: ["session"],
    accessProfile: (scope, checkIds) => ["access-profile", scope, ...checkIds],
    diagnostics: ["settings", "diagnostics"],
    workspaceSettings: ["settings", "workspace"],
    sites: ["settings", "sites"],
    audit: (filter) => ["operations", "audit", filter],
    retentionPolicy: ["operations", "retention", "policy"],
    retentionPlan: (id) => ["operations", "retention", "plan", id],
    plugins: ["plugins", "catalog"],
    pluginExtensions: ["plugins", "extensions"],
    collections: ["collections"],
    schemaManifest: ["schema", "manifest"],
    schemaTypes: ["schema", "types"],
    media: ["media"],
    collectionDraft: (collectionId) => ["collections", collectionId, "draft"],
    collectionApplied: (collectionId) => ["collections", collectionId, "applied"],
    migration: (collectionId, draftVersion) => ["collections", collectionId, "migration", draftVersion],
    documentsRoot: (collectionId) => ["documents", collectionId],
    documentTree: (collectionId) => ["documents", collectionId, "tree"],
    relationOptions: (collectionIds) => ["documents", "relation-options", ...collectionIds],
    documents: (collectionId, page, state = "active") => ["documents", collectionId, "state", state, "page", page],
    document: (collectionId, documentId) => ["documents", collectionId, documentId],
    revisionsRoot: (collectionId, documentId) => ["documents", collectionId, documentId, "revisions"],
    revisions: (collectionId, documentId) => ["documents", collectionId, documentId, "revisions", "list"],
    revision: (collectionId, documentId, revisionId) => ["documents", collectionId, documentId, "revisions", revisionId],
    authorization: ["authorization", "system", "policy"],
    authorizationAudit: ["authorization", "system", "audit"],
    realmAuthorization: (realmId) => ["authorization", "realm", realmId, "policy"],
    realmAuthorizationAudit: (realmId) => ["authorization", "realm", realmId, "audit"],
    globalIdentities: ["identity-realms", "global-identities"],
    identities: (query = "", status = "all") => ["identities", "list", query, status],
    identity: (identityId) => ["identities", identityId],
    identitySessionsRoot: (identityId) => ["identities", identityId, "sessions"],
    identitySessions: (identityId, status, page) => ["identities", identityId, "sessions", status, page],
    identityApiKeys: (identityId) => ["identities", identityId, "api-keys"],
    identityRealms: ["identity-realms", "list"],
    identityRealm: (realmId) => ["identity-realms", realmId, "detail"],
    realmMemberships: (realmId) => ["identity-realms", realmId, "memberships"],
    realmOwner: (realmId) => ["identity-realms", realmId, "owner"],
    realmFullAccess: (realmId) => ["identity-realms", realmId, "full-access"],
    realmEntitlements: (realmId) => ["identity-realms", realmId, "collection-entitlements"],
    collectionEntitlements: (collectionId) => ["collections", collectionId, "entitlements"],
    jobs: (page, status, topic, handlerId) => ["jobs", "list", page, status, topic, handlerId],
};
//# sourceMappingURL=queries.js.map