import { readFile,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PostgresDatabase,qualifiedName } from "@xecms/database";
import { generateTypeScriptTypes,parseSchema,serializeSchema } from "@xecms/schema";
import { createBackup,restoreBackup } from "./backup.js";
import { cliError,loadProject } from "./config.js";
import { doctor } from "./doctor.js";
import { scaffold } from "./scaffold.js";
import { isStarterName } from "./starters.js";

export interface CliIo{log(value:string):void;error(value:string):void}
const defaultIo:CliIo={log:value=>console.log(value),error:value=>console.error(value)};
export async function main(input=process.argv.slice(2),io=defaultIo):Promise<number>{try{const args=[...input],cwd=takeOption(args,"--cwd")??process.cwd(),command=args.shift();if(!command||command==="help"||command==="--help"||command==="-h"){io.log(help());return 0}if(command==="version"||command==="--version"||command==="-v"){io.log("XeCMS 0.4.0 (Plugin SDK 1.0.0, backup format 1)");return 0}
  if(command==="init"){const directory=args.shift()??cwd,starter=takeOption(args,"--starter")??"minimal";if(!isStarterName(starter))throw cliError("STARTER_INVALID",`Unknown starter '${starter}'. Use minimal, blog or community.`);assertNoArgs(args);const root=await scaffold(directory,starter);io.log(`Created XeCMS ${starter} project at ${root}`);return 0}
  const project=await loadProject(cwd,!(command==="schema"&&args[0]==="validate")&&command!=="generate");
  if(command==="migrate"){assertNoArgs(args);const database=new PostgresDatabase({connectionString:project.databaseUrl,schema:project.config.databaseSchema});try{await database.migrate();io.log(`Core migrations are current for schema '${database.schema}'.`)}finally{await database.close()}return 0}
  if(command==="schema"){const action=args.shift()??"validate";if(action==="validate"){const file=resolve(project.root,args.shift()??project.config.schemaFile);assertNoArgs(args);const schema=parseSchema(await readFile(file,"utf8"));io.log(`Valid XeCMS Schema: ${schema.collections.length} collections (${file})`);return 0}if(action==="export"){const file=resolve(project.root,args.shift()??project.config.schemaFile);assertNoArgs(args);const schema=await activeSchema(project.databaseUrl,project.config.databaseSchema);await writeFile(file,serializeSchema(schema),"utf8");io.log(`Exported active Schema to ${file}`);return 0}throw cliError("COMMAND_INVALID",`Unknown schema action '${action}'.`)}
  if(command==="generate"){if(args.shift()!=="types")throw cliError("COMMAND_INVALID","Use 'xecms generate types'.");const source=takeOption(args,"--source")??"file",output=resolve(project.root,takeOption(args,"--output")??project.config.typesFile);assertNoArgs(args);const schema=source==="active"?await activeSchema(requireDatabase(project),project.config.databaseSchema):source==="file"?parseSchema(await readFile(resolve(project.root,project.config.schemaFile),"utf8")):(()=>{throw cliError("TYPE_SOURCE_INVALID","--source must be file or active.")})();await writeFile(output,generateTypeScriptTypes(schema),"utf8");io.log(`Generated types for ${schema.collections.length} collections at ${output}`);return 0}
  if(command==="doctor"){const json=takeFlag(args,"--json");assertNoArgs(args);const report=await doctor(project);if(json)io.log(JSON.stringify(report,null,2));else{for(const check of report.checks)io.log(`${symbol(check.status)} ${check.id}: ${check.message}`);io.log(`Doctor: ${report.status}`)}return report.status==="healthy"?0:1}
  if(command==="backup"){const action=args.shift(),directory=args.shift();if(!directory)throw cliError("BACKUP_DIRECTORY_REQUIRED","Backup directory is required.");if(action==="create"){assertNoArgs(args);const manifest=await createBackup(project,directory);io.log(`Backup ${manifest.createdAt} created at ${resolve(project.root,directory)}`);return 0}if(action==="restore"){const confirmed=takeFlag(args,"--confirm-empty");assertNoArgs(args);await restoreBackup(project,directory,confirmed);io.log(`Backup restored into empty schema '${project.config.databaseSchema}'. Run xecms doctor before starting the server.`);return 0}throw cliError("COMMAND_INVALID","Use 'xecms backup create|restore <directory>'.")}
  if(command==="dev"){assertNoArgs(args);process.env["XECMS_DB_SCHEMA"]??=project.config.databaseSchema;process.env["XECMS_MEDIA_STORAGE_ROOT"]??=resolve(project.root,project.config.mediaStorageRoot);process.env["XECMS_ADMIN_DIST"]??=resolve(project.root,project.config.adminDist);const{buildServer}=await import("@xecms/server");const server=await buildServer();const stop=()=>void server.close();process.once("SIGINT",stop);process.once("SIGTERM",stop);await server.app.listen({host:server.config.host,port:server.config.port});io.log(`XeCMS is running at http://${server.config.host}:${server.config.port}/admin/`);return await new Promise<number>(()=>undefined)}
  throw cliError("COMMAND_INVALID",`Unknown command '${command}'. Run xecms help.`)
 }catch(error){const code=typeof error==="object"&&error!==null&&"code" in error?String((error as{code:unknown}).code):"UNEXPECTED_ERROR";io.error(`[${code}] ${error instanceof Error?error.message:String(error)}`);return 1}}
function takeOption(args:string[],name:string){const index=args.indexOf(name);if(index<0)return undefined;const value=args[index+1];if(!value||value.startsWith("--"))throw cliError("OPTION_VALUE_REQUIRED",`${name} requires a value.`);args.splice(index,2);return value}
function takeFlag(args:string[],name:string){const index=args.indexOf(name);if(index<0)return false;args.splice(index,1);return true}
function assertNoArgs(args:readonly string[]){if(args.length)throw cliError("ARGUMENT_UNEXPECTED",`Unexpected argument '${args[0]}'.`)}
function symbol(status:"pass"|"warn"|"fail"){return status==="pass"?"PASS":status==="warn"?"WARN":"FAIL"}
function requireDatabase(project:Awaited<ReturnType<typeof loadProject>>){if(!project.databaseUrl)throw cliError("DATABASE_URL_REQUIRED","DATABASE_URL is required for active Schema generation.");return project.databaseUrl}
async function activeSchema(databaseUrl:string,schema:string){const database=new PostgresDatabase({connectionString:databaseUrl,schema,maxConnections:2});try{const state=qualifiedName(database.schema,"_xecms_schema_state"),revisions=qualifiedName(database.schema,"_xecms_schema_revisions");const result=await database.pool.query<{schema_json:unknown}>(`SELECT revision.schema_json FROM ${state} state JOIN ${revisions} revision ON revision.revision_id=state.active_revision_id WHERE state.singleton=true`);if(!result.rows[0])throw cliError("SCHEMA_NOT_FOUND","No active Schema exists.");return parseSchema(JSON.stringify(result.rows[0].schema_json))}finally{await database.close()}}
function help(){return`XeCMS 0.4.0\n\nCommands:\n  init [directory] --starter minimal|blog|community\n  dev\n  migrate\n  schema validate [file]\n  schema export [file]\n  generate types [--source file|active] [--output file]\n  doctor [--json]\n  backup create <directory>\n  backup restore <directory> --confirm-empty\n  version\n\nGlobal: --cwd <project-directory>`}
