import { mkdtemp,readFile,rm,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach,describe,expect,it } from "vitest";
import { parseSchema } from "@xecms/schema";
import { main } from "./cli.js";
import { scaffold } from "./scaffold.js";

const roots:string[]=[];afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))});
async function temp(){const root=await mkdtemp(resolve(tmpdir(),"xecms-cli-"));roots.push(root);return root}
describe("XeCMS CLI scaffold",()=>{
  it("reports the current release version",async()=>{const output:string[]=[];expect(await main(["version"],{log:value=>output.push(value),error:()=>undefined})).toBe(0);expect(output).toEqual(["XeCMS 0.5.0 (Plugin SDK 1.0.0, backup format 1)"])});
  it.each(["minimal","blog","community"] as const)("creates and builds the %s starter",async starter=>{const parent=await temp(),root=resolve(parent,starter);await scaffold(root,starter);const schema=parseSchema(await readFile(resolve(root,"xecms.schema.json"),"utf8"));expect(schema.collections.length).toBe(starter==="minimal"?0:starter==="blog"?3:2);expect(await readFile(resolve(root,".env"),"utf8")).not.toContain("XECMS_DEV_SEED");const readme=await readFile(resolve(root,"README.md"),"utf8");expect(readme).toContain("/admin/setup");expect(readme).toContain("pnpm start");const packageJson=JSON.parse(await readFile(resolve(root,"package.json"),"utf8")) as {scripts:Record<string,string>};expect(packageJson.scripts["start"]).toBe("xecms start");const output:string[]=[],errors:string[]=[];expect(await main(["--cwd",root,"schema","validate"],{log:value=>output.push(value),error:value=>errors.push(value)})).toBe(0);expect(await main(["--cwd",root,"generate","types"],{log:value=>output.push(value),error:value=>errors.push(value)})).toBe(0);expect(await readFile(resolve(root,"xecms.generated.ts"),"utf8")).toContain("This file is generated by XeCMS");expect(errors).toEqual([])});
  it("generates a compose healthcheck that probes the published TCP port",async()=>{
    // pg_isready over the unix socket reports healthy while Postgres is still
    // initialising and TCP is closed, so `up --wait` returned before clients
    // could connect and the first migrate died on ECONNREFUSED.
    const root=await temp();await scaffold(root,"minimal");
    const compose=await readFile(resolve(root,"compose.yaml"),"utf8");
    expect(compose).toContain("pg_isready -h 127.0.0.1 -p 5432");
    expect(compose).toContain("start_period:");
  });
  it("documents the Plugin drift recovery command and rejects unknown actions",async()=>{
    // The server refuses to boot on manifest drift, which locks Admin Studio;
    // `plugin sync` is the only recovery path, so it must be discoverable.
    const output:string[]=[];
    expect(await main(["help"],{log:value=>output.push(value),error:()=>undefined})).toBe(0);
    expect(output.join("\n")).toContain("plugin sync [--apply]");
    expect(output.join("\n")).toContain("start");
    expect(output.join("\n")).toContain("XECMS_ENV_FILE");
    const root=await temp();await scaffold(root,"minimal");
    const errors:string[]=[];
    expect(await main(["--cwd",root,"plugin","bogus"],{log:()=>undefined,error:value=>errors.push(value)})).toBe(1);
    expect(errors[0]).toContain("[COMMAND_INVALID]");
  });
  it("refuses non-empty targets and reports stable CLI errors",async()=>{const root=await temp();await writeFile(resolve(root,"owned.txt"),"keep");const errors:string[]=[];expect(await main(["init",root],{log:()=>undefined,error:value=>errors.push(value)})).toBe(1);expect(errors[0]).toContain("[DIRECTORY_NOT_EMPTY]");expect(await readFile(resolve(root,"owned.txt"),"utf8")).toBe("keep")});
});
