import { createHash } from "node:crypto";
import { access,mkdir,readFile,rm,writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { resolve } from "node:path";
import { spawn } from "node:child_process";
import { CORE_MIGRATION_IDS,PostgresDatabase,qualifiedName } from "@xecms/database";
import { pluginManifestDigest,type XeCmsPluginManifestV1 } from "@xecms/plugin-sdk";
import { serializeSchema,parseSchema } from "@xecms/schema";
import type { LoadedProject } from "./config.js";

export type DoctorStatus="pass"|"warn"|"fail";
export interface DoctorCheck{readonly id:string;readonly status:DoctorStatus;readonly message:string;readonly details?:Readonly<Record<string,unknown>>}
export interface DoctorReport{readonly status:"healthy"|"degraded";readonly version:"0.4.0";readonly checkedAt:string;readonly checks:readonly DoctorCheck[]}
export async function doctor(project:LoadedProject):Promise<DoctorReport>{const checks:DoctorCheck[]=[];checks.push(nodeCheck());const database=new PostgresDatabase({connectionString:project.databaseUrl,schema:project.config.databaseSchema,maxConnections:3});try{
  const version=await database.pool.query<{version:string}>("SELECT current_setting('server_version') version");checks.push(ok("database",`PostgreSQL ${version.rows[0]!.version} connection succeeded.`));
  const q=(name:string)=>qualifiedName(database.schema,name);const migrations=await database.pool.query<{id:string}>(`SELECT id FROM ${q("_xecms_core_migrations")} ORDER BY id`);const actual=migrations.rows.map(row=>row.id),missing=CORE_MIGRATION_IDS.filter(id=>!actual.includes(id)),unknown=actual.filter(id=>!CORE_MIGRATION_IDS.includes(id as never));checks.push(missing.length||unknown.length?fail("migrations","Core migration history does not match this release.",{missing,unknown}):ok("migrations",`${actual.length} core migrations match release 0.4.0.`));
  const active=await database.pool.query<{hash:string;schema_json:unknown}>(`SELECT revision.hash,revision.schema_json FROM ${q("_xecms_schema_state")} state JOIN ${q("_xecms_schema_revisions")} revision ON revision.revision_id=state.active_revision_id WHERE state.singleton=true`);const schemaPath=resolve(project.root,project.config.schemaFile);if(active.rows[0]){try{const file=parseSchema(await readFile(schemaPath,"utf8")),fileHash=sha(serializeSchema(file)),activeHash=active.rows[0].hash;checks.push(fileHash===activeHash?ok("schema",`Project Manifest matches active Schema ${activeHash.slice(0,12)}.`):warn("schema","Project Manifest differs from the active Schema.",{projectHash:fileHash,activeHash}))}catch(error){checks.push(fail("schema",`Project Manifest cannot be read: ${message(error)}`))}}else checks.push(warn("schema","No active Schema exists; apply the starter Manifest in Admin Studio."));
  const plugins=await database.pool.query<{plugin_id:string;manifest:XeCmsPluginManifestV1;manifest_digest:string;desired_state:string}>(`SELECT plugin_id,manifest,manifest_digest,desired_state FROM ${q("_xecms_plugins")} ORDER BY plugin_id`);const pluginIssues:string[]=[];for(const plugin of plugins.rows){if(pluginManifestDigest(plugin.manifest)!==plugin.manifest_digest)pluginIssues.push(`${plugin.plugin_id}: manifest digest drift`);const history=await database.pool.query<{migration_id:string;checksum:string}>(`SELECT migration_id,checksum FROM ${q("_xecms_plugin_migrations")} WHERE workspace_id='wrk_default' AND plugin_id=$1 ORDER BY sequence`,[plugin.plugin_id]);const expected=(plugin.manifest.migrations??[]).map(x=>`${x.id}:${x.checksum}`),found=history.rows.map(x=>`${x.migration_id}:${x.checksum}`);if(JSON.stringify(expected)!==JSON.stringify(found))pluginIssues.push(`${plugin.plugin_id}: migration history drift`)}checks.push(pluginIssues.length?fail("plugins","Plugin integrity checks failed.",{issues:pluginIssues}):ok("plugins",`${plugins.rowCount??0} installed Plugin records are consistent.`));
  const worker=await database.pool.query<{pending:string;dead:string}>(`SELECT (SELECT count(*)::text FROM ${q("_xecms_outbox_events")} WHERE dispatched_at IS NULL) pending,(SELECT count(*)::text FROM ${q("_xecms_event_deliveries")} WHERE status='dead') dead`);const pending=Number(worker.rows[0]!.pending),dead=Number(worker.rows[0]!.dead);checks.push(dead>0?warn("worker",`Worker has ${dead} dead deliveries.`,{pending,dead}):ok("worker",`Worker queues are readable (${pending} pending, ${dead} dead).`));
 }catch(error){checks.push(fail("database",`Database diagnostics failed: ${message(error)}`))}finally{await database.close()}
 checks.push(await storageCheck(resolve(project.root,project.config.mediaStorageRoot)));checks.push(configCheck());checks.push(await backupToolsCheck(project.root));return{status:checks.some(check=>check.status==="fail")?"degraded":"healthy",version:"0.4.0",checkedAt:new Date().toISOString(),checks}}
function nodeCheck(){const [major,minor]=process.versions.node.split(".").map(Number);return major!>22||major===22&&minor!>=13?ok("runtime",`Node.js ${process.versions.node} is supported.`):fail("runtime",`Node.js ${process.versions.node} is unsupported; use >=22.13.0.`)}
function configCheck(){const production=process.env["NODE_ENV"]==="production",secret=process.env["XECMS_SESSION_SECRET"]??"";return production&&Buffer.byteLength(secret)<32?fail("configuration","Production session secret must contain at least 32 bytes."):ok("configuration",production?"Production secret baseline passed.":"Development configuration loaded.")}
async function storageCheck(root:string):Promise<DoctorCheck>{const probe=resolve(root,`.doctor-${process.pid}`);try{await mkdir(root,{recursive:true});await access(root,constants.R_OK|constants.W_OK);await writeFile(probe,"xecms-doctor",{flag:"wx"});await rm(probe);return ok("storage",`Media storage is readable and writable at ${root}.`)}catch(error){await rm(probe,{force:true}).catch(()=>undefined);return fail("storage",`Media storage check failed: ${message(error)}`)}}
async function backupToolsCheck(cwd:string):Promise<DoctorCheck>{try{for(const[variable,fallback]of [["XECMS_PG_DUMP_COMMAND_JSON","pg_dump"],["XECMS_PG_RESTORE_COMMAND_JSON","pg_restore"],["XECMS_TAR_COMMAND_JSON","tar"]] as const){const parts=process.env[variable]?JSON.parse(process.env[variable]!) as string[]:[fallback];if(!Array.isArray(parts)||!parts.length)throw new Error(`${variable} is invalid`);await executable(parts,cwd)}return ok("backup-tools","pg_dump, pg_restore and tar commands are executable.")}catch(error){return fail("backup-tools",`Backup tool check failed: ${message(error)}`)}}
function executable(parts:readonly string[],cwd:string){return new Promise<void>((resolvePromise,reject)=>{const child=spawn(parts[0]!,[...parts.slice(1),"--version"],{cwd,stdio:"ignore"});child.once("error",reject);child.once("exit",code=>code===0?resolvePromise():reject(new Error(`${parts[0]} --version exited ${code}`)))})}
const ok=(id:string,message:string,details?:Readonly<Record<string,unknown>>):DoctorCheck=>({id,status:"pass",message,...(details?{details}:{})});const warn=(id:string,message:string,details?:Readonly<Record<string,unknown>>):DoctorCheck=>({id,status:"warn",message,...(details?{details}:{})});const fail=(id:string,message:string,details?:Readonly<Record<string,unknown>>):DoctorCheck=>({id,status:"fail",message,...(details?{details}:{})});
function sha(value:string){return createHash("sha256").update(value).digest("hex")}function message(error:unknown){return error instanceof Error?error.message:String(error)}
