import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Button } from "@xecms/ui";
import styles from "../../authorization.module.css";
import { permissionCategoryName, permissionTaskName } from "./vocabulary.js";
export function PermissionEditor({ permissions, selected, delegated, query, technical, advanced, readOnly, onQueryChange, onTechnicalChange, onPermissionChange, onDelegationChange, }) {
    const groups = new Map();
    for (const permission of permissions) {
        groups.set(permission.category, [...(groups.get(permission.category) ?? []), permission]);
    }
    const modeOf = (key) => delegated.includes(key)
        ? "delegate"
        : selected.includes(key) ? "use" : "none";
    const setMode = (key, mode) => {
        onPermissionChange(key, mode !== "none");
        onDelegationChange(key, mode === "delegate");
    };
    return (_jsxs("div", { className: styles.permissionEditor, children: [_jsxs("div", { className: styles.permissionToolbar, children: [_jsxs("div", { className: styles.permissionSummary, children: [_jsxs("strong", { children: [selected.length, "\uAC1C \uC5C5\uBB34 \uD5C8\uC6A9"] }), advanced ? _jsxs("span", { children: [delegated.length, "\uAC1C\uB294 \uD558\uC704 \uC5ED\uD560\uC5D0 \uC704\uC784 \uAC00\uB2A5"] }) : null] }), _jsxs("div", { className: styles.permissionTools, children: [_jsxs("label", { className: styles.permissionSearch, children: [_jsx("span", { className: styles.visuallyHidden, children: "\uAD8C\uD55C \uAC80\uC0C9" }), _jsx("input", { value: query, onChange: (event) => onQueryChange(event.target.value), placeholder: "\uC5C5\uBB34 \uB610\uB294 \uAD8C\uD55C \uAC80\uC0C9" })] }), advanced ? (_jsx(Button, { size: "small", variant: "secondary", onPress: () => onTechnicalChange(!technical), children: technical ? "업무별 간편 보기" : "권한 코드 보기" })) : null] })] }), advanced && technical ? (_jsxs("div", { className: styles.permissionMatrix, children: [_jsxs("div", { className: styles.permissionHeader, children: [_jsx("span", { children: "\uAD8C\uD55C \uCF54\uB4DC" }), _jsx("span", { children: "\uC0AC\uC6A9" }), _jsx("span", { children: "\uC704\uC784" })] }), permissions.map((permission) => (_jsxs("div", { className: styles.permissionRow, children: [_jsxs("span", { className: styles.permissionName, children: [_jsx("code", { children: permission.key }), _jsxs("span", { children: [permissionTaskName(permission.key), " \u00B7 ", permissionCategoryName(permission.category)] })] }), _jsx("label", { className: styles.checkboxCell, children: _jsx("input", { "aria-label": `${permission.key} 사용`, type: "checkbox", checked: selected.includes(permission.key), disabled: readOnly, onChange: (event) => onPermissionChange(permission.key, event.target.checked) }) }), _jsx("label", { className: styles.checkboxCell, children: _jsx("input", { "aria-label": `${permission.key} 위임`, type: "checkbox", checked: delegated.includes(permission.key), disabled: readOnly || !selected.includes(permission.key) || !permission.delegatable || permission.protected, onChange: (event) => onDelegationChange(permission.key, event.target.checked) }) })] }, permission.key))), permissions.length === 0 ? _jsx("div", { className: styles.permissionEmpty, children: "\uAC80\uC0C9 \uC870\uAC74\uC5D0 \uB9DE\uB294 \uAD8C\uD55C\uC774 \uC5C6\uC2B5\uB2C8\uB2E4." }) : null] })) : (_jsxs("div", { className: styles.permissionGroups, children: [[...groups.entries()].map(([category, items]) => {
                        const selectedCount = items.filter(({ key }) => selected.includes(key)).length;
                        return (_jsxs("section", { className: styles.permissionGroup, children: [_jsxs("div", { className: styles.permissionGroupHeader, children: [_jsxs("div", { children: [_jsx("strong", { children: permissionCategoryName(category) }), _jsxs("span", { children: [items.length, "\uAC1C \uC5C5\uBB34"] })] }), _jsxs(Badge, { tone: selectedCount > 0 ? "success" : "neutral", children: [selectedCount, "\uAC1C \uD5C8\uC6A9"] })] }), _jsx("div", { className: styles.permissionTaskList, children: items.map((permission) => {
                                        const mode = modeOf(permission.key);
                                        return (_jsxs("article", { className: styles.permissionTask, "data-enabled": mode !== "none", children: [_jsxs("div", { className: styles.permissionTaskIdentity, children: [_jsx("strong", { children: permissionTaskName(permission.key) }), advanced ? _jsx("code", { children: permission.key }) : null, advanced && permission.hierarchyGuard !== "none" ? _jsx("span", { children: "\uB300\uC0C1\uACFC\uC758 \uAD8C\uD55C \uB808\uBCA8\uC744 \uD568\uAED8 \uD655\uC778\uD569\uB2C8\uB2E4." }) : null] }), advanced ? (_jsx("div", { className: styles.permissionModes, role: "radiogroup", "aria-label": `${permissionTaskName(permission.key)} 권한 수준`, children: ["none", "use", "delegate"].map((option) => {
                                                        const disabled = readOnly || (option === "delegate" && (!permission.delegatable || permission.protected));
                                                        const label = option === "none" ? "허용 안 함" : option === "use" ? "사용" : "사용 + 위임";
                                                        return (_jsxs("label", { "data-selected": mode === option, "data-disabled": disabled, children: [_jsx("input", { type: "radio", name: `permission-${permission.key}`, value: option, checked: mode === option, disabled: disabled, onChange: () => setMode(permission.key, option) }), _jsx("span", { children: label })] }, option));
                                                    }) })) : (_jsxs("label", { className: styles.standardPermissionToggle, "data-selected": selected.includes(permission.key), children: [_jsx("input", { type: "checkbox", "aria-label": `${permissionTaskName(permission.key)} 허용`, checked: selected.includes(permission.key), disabled: readOnly, onChange: (event) => onPermissionChange(permission.key, event.target.checked) }), _jsx("span", { children: selected.includes(permission.key) ? "허용됨" : "허용" })] }))] }, permission.key));
                                    }) })] }, category));
                    }), permissions.length === 0 ? _jsx("div", { className: styles.permissionEmpty, children: "\uAC80\uC0C9 \uC870\uAC74\uC5D0 \uB9DE\uB294 \uC5C5\uBB34\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4." }) : null] }))] }));
}
//# sourceMappingURL=permission-editor.js.map