import { randomUUID } from "node:crypto";
import { ApplicationError, SYSTEM_AUTHORIZATION_REALM_ID, type PluginBlocker, type PluginDataAction,
  type PluginPlan, type PluginPlanAction, type PluginRecord, type PluginStore } from "@xecms/application";
import { pluginManifestDigest, type PluginMigrationContext, type XeCmsPluginManifestV1,
  type XeCmsPluginModule } from "@xecms/plugin-sdk";
import type { Pool, PoolClient, QueryResultRow } from "pg";
import { qualifiedName, validateDatabaseSchema } from "./identifiers.js";

export class PostgresPluginStore implements PluginStore{
  private readonly schema:string;
  public constructor(private readonly pool:Pool,schema:string){this.schema=validateDatabaseSchema(schema)}
  public async list(workspaceId:string){const result=await this.pool.query<PluginRow>(`SELECT * FROM ${this.q("_xecms_plugins")} WHERE workspace_id=$1 ORDER BY plugin_id`,[workspaceId]);return result.rows.map(mapPlugin)}
  public async get(workspaceId:string,pluginId:string){const result=await this.pool.query<PluginRow>(`SELECT * FROM ${this.q("_xecms_plugins")} WHERE workspace_id=$1 AND plugin_id=$2`,[workspaceId,pluginId]);return result.rows[0]?mapPlugin(result.rows[0]):null}
  public async assertMigrationState(workspaceId:string,module:XeCmsPluginModule){const result=await this.pool.query<{migration_id:string;checksum:string;sequence:number|string}>(`SELECT migration_id,checksum,sequence FROM ${this.q("_xecms_plugin_migrations")} WHERE workspace_id=$1 AND plugin_id=$2 ORDER BY sequence`,[workspaceId,module.manifest.id]);const actual=result.rows.map(row=>({id:row.migration_id,checksum:row.checksum,sequence:Number(row.sequence)}));const expected=(module.manifest.migrations??[]).map((migration,index)=>({id:migration.id,checksum:migration.checksum,sequence:index+1}));if(JSON.stringify(actual)!==JSON.stringify(expected))throw new ApplicationError("PLUGIN_MIGRATION_CHECKSUM_DRIFT",503,`Plugin '${module.manifest.id}' migration history does not match its manifest.`,{details:{expected,actual}})}
  public async markRuntimeReconciled(workspaceId:string,loadedPluginIds:readonly string[]){await this.pool.query(`UPDATE ${this.q("_xecms_plugins")} SET restart_required=false WHERE workspace_id=$1 AND ((desired_state='enabled' AND plugin_id=ANY($2::text[])) OR (desired_state<>'enabled' AND NOT(plugin_id=ANY($2::text[]))))`,[workspaceId,loadedPluginIds])}
  public async updateConfig(input:Parameters<PluginStore["updateConfig"]>[0]){const client=await this.pool.connect();try{await client.query("BEGIN");const current=await this.lockPlugin(client,input.workspaceId,input.pluginId);this.assertExpected(current,input.expectedRevision);const result=await client.query<PluginRow>(`UPDATE ${this.q("_xecms_plugins")} SET config=$3::jsonb,revision=revision+1,restart_required=true,updated_at=$4,updated_by=$5 WHERE workspace_id=$1 AND plugin_id=$2 RETURNING *`,[input.workspaceId,input.pluginId,JSON.stringify(input.config),input.now,input.actorIdentityId]);const record=mapPlugin(result.rows[0]!);await this.audit(client,"plugin.config.updated",record,input.actorIdentityId,input.actorSubjectId,input.now,{configKeys:Object.keys(input.config)});await client.query("COMMIT");return record}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
  public async createPlan(input:Parameters<PluginStore["createPlan"]>[0]){const client=await this.pool.connect();try{await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ");const current=await this.findPlugin(client,input.workspaceId,input.module.manifest.id,true);this.assertExpected(current,input.expectedPluginRevision);const snapshot=await this.snapshot(client,input.workspaceId,input.module,input.action,input.dataAction,current);const digest=planDigest(input.module,input.action,input.dataAction,input.expectedPluginRevision,snapshot);const result=await client.query<PlanRow>(`INSERT INTO ${this.q("_xecms_plugin_plans")}(id,workspace_id,plugin_id,action,data_action,expected_plugin_revision,manifest_digest,status,blockers,dependency_ids,schema_references,data_counts,migration_ids,digest,created_at,created_by,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,'previewed',$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13,$14,$15,$16) RETURNING *`,[input.id,input.workspaceId,input.module.manifest.id,input.action,input.dataAction??null,input.expectedPluginRevision,pluginManifestDigest(input.module.manifest),JSON.stringify(snapshot.blockers),JSON.stringify(snapshot.dependencyIds),JSON.stringify(snapshot.schemaReferences),JSON.stringify(snapshot.dataCounts),JSON.stringify(snapshot.migrationIds),digest,input.createdAt,input.createdBy,input.expiresAt]);await client.query("COMMIT");return mapPlan(result.rows[0]!)}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
  public async getPlan(workspaceId:string,planId:string){const result=await this.pool.query<PlanRow>(`SELECT * FROM ${this.q("_xecms_plugin_plans")} WHERE workspace_id=$1 AND id=$2`,[workspaceId,planId]);return result.rows[0]?mapPlan(result.rows[0]):null}
  public async applyPlan(input:Parameters<PluginStore["applyPlan"]>[0]){const client=await this.pool.connect();try{await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ");const planResult=await client.query<PlanRow>(`SELECT * FROM ${this.q("_xecms_plugin_plans")} WHERE workspace_id=$1 AND id=$2 FOR UPDATE`,[input.workspaceId,input.planId]);if(!planResult.rows[0])throw new ApplicationError("PLUGIN_PLAN_NOT_FOUND",404,"Plugin lifecycle plan does not exist.");const plan=mapPlan(planResult.rows[0]);if(plan.status==="applied"){await client.query("COMMIT");return plan}if(Date.parse(plan.expiresAt)<=Date.parse(input.now))throw new ApplicationError("PLUGIN_PLAN_EXPIRED",409,"Plugin lifecycle plan expired.");if(plan.pluginId!==input.module.manifest.id||plan.manifestDigest!==pluginManifestDigest(input.module.manifest))throw new ApplicationError("PLUGIN_MANIFEST_DRIFT",409,"Plugin manifest changed after preview.");if(plan.expectedPluginRevision!==input.expectedPluginRevision)throw new ApplicationError("PLUGIN_PLAN_REVISION_MISMATCH",409,"Apply revision does not match preview.");const current=await this.findPlugin(client,input.workspaceId,plan.pluginId,true);this.assertExpected(current,input.expectedPluginRevision);const snapshot=await this.snapshot(client,input.workspaceId,input.module,plan.action,plan.dataAction,current);const digest=planDigest(input.module,plan.action,plan.dataAction,plan.expectedPluginRevision,snapshot);if(digest!==plan.digest)throw new ApplicationError("PLUGIN_PLAN_STALE",409,"Plugin lifecycle candidates changed after preview.",{details:{previewDigest:plan.digest,currentDigest:digest}});if(snapshot.blockers.length)throw new ApplicationError("PLUGIN_PLAN_BLOCKED",409,"Plugin lifecycle plan has blockers.",{details:{blockers:snapshot.blockers}});
      let record:PluginRecord|null=current?mapPlugin(current):null,exportId:string|undefined;
      if(plan.action==="install")record=await this.install(client,input.workspaceId,input.module,input.actorIdentityId,input.actorSubjectId,input.now);
      else if(plan.action==="enable"||plan.action==="disable")record=await this.setState(client,input.workspaceId,plan.pluginId,plan.action==="enable"?"enabled":"disabled",input.expectedPluginRevision!,input.actorIdentityId,input.actorSubjectId,input.now);
      else{const removed=await this.uninstall(client,input.workspaceId,input.module,plan.dataAction!,input.actorIdentityId,input.actorSubjectId,input.now);exportId=removed.exportId;record=null}
      const updated=await client.query<PlanRow>(`UPDATE ${this.q("_xecms_plugin_plans")} SET status='applied',applied_at=$3,applied_by=$4,result=$5::jsonb,export_id=$6 WHERE workspace_id=$1 AND id=$2 RETURNING *`,[input.workspaceId,input.planId,input.now,input.actorIdentityId,JSON.stringify(record),exportId??null]);await client.query("COMMIT");return mapPlan(updated.rows[0]!)}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
  public async getExport(workspaceId:string,exportId:string){const result=await this.pool.query<{id:string;plugin_id:string;created_at:Date|string;data:unknown}>(`SELECT id,plugin_id,created_at,data FROM ${this.q("_xecms_plugin_exports")} WHERE workspace_id=$1 AND id=$2`,[workspaceId,exportId]);const row=result.rows[0];return row?{id:row.id,pluginId:row.plugin_id,createdAt:new Date(row.created_at).toISOString(),data:row.data}:null}

  private async install(client:PoolClient,workspaceId:string,module:XeCmsPluginModule,identityId:string,subjectId:string,now:string){for(const [index,migration] of (module.server?.migrations??[]).entries()){const existing=await client.query<{checksum:string}>(`SELECT checksum FROM ${this.q("_xecms_plugin_migrations")} WHERE workspace_id=$1 AND plugin_id=$2 AND migration_id=$3`,[workspaceId,module.manifest.id,migration.id]);if(existing.rows[0]&&existing.rows[0].checksum!==migration.checksum)throw new ApplicationError("PLUGIN_MIGRATION_CHECKSUM_DRIFT",409,`Migration '${migration.id}' checksum changed.`);if(existing.rows[0])continue;await migration.up(this.migrationContext(client));await client.query(`INSERT INTO ${this.q("_xecms_plugin_migrations")}(workspace_id,plugin_id,migration_id,checksum,sequence,applied_at,applied_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[workspaceId,module.manifest.id,migration.id,migration.checksum,index+1,now,identityId])}for(const permission of module.manifest.extensions?.permissions??[]){await client.query(`INSERT INTO ${this.q("_xecms_auth_permissions")}(permission_key,hierarchy_guard,delegatable,protected,created_at) VALUES($1,'none',true,false,$2) ON CONFLICT(permission_key) DO NOTHING`,[permission,now]);await client.query(`INSERT INTO ${this.q("_xecms_auth_role_permissions")}(realm_id,role_id,permission_key) SELECT realm_id,id,$1 FROM ${this.q("_xecms_auth_roles")} WHERE id IN ('authorization:'||realm_id||':role:owner','authorization:'||realm_id||':role:administrator') ON CONFLICT DO NOTHING`,[permission]);await client.query(`INSERT INTO ${this.q("_xecms_auth_role_delegations")}(realm_id,role_id,permission_key) SELECT role.realm_id,role.id,$1 FROM ${this.q("_xecms_auth_roles")} role JOIN ${this.q("_xecms_auth_permissions")} permission ON permission.permission_key=$1 WHERE role.id='authorization:'||role.realm_id||':role:owner' AND permission.delegatable=true AND permission.protected=false ON CONFLICT DO NOTHING`,[permission])}const result=await client.query<PluginRow>(`INSERT INTO ${this.q("_xecms_plugins")}(workspace_id,plugin_id,package_name,version,manifest,manifest_digest,desired_state,config,revision,restart_required,installed_at,installed_by,updated_at,updated_by) VALUES($1,$2,$3,$4,$5::jsonb,$6,'installed','{}'::jsonb,1,true,$7,$8,$7,$8) RETURNING *`,[workspaceId,module.manifest.id,module.manifest.packageName,module.manifest.version,JSON.stringify(module.manifest),pluginManifestDigest(module.manifest),now,identityId]);const record=mapPlugin(result.rows[0]!);await this.audit(client,"plugin.installed",record,identityId,subjectId,now,{migrationIds:(module.manifest.migrations??[]).map(x=>x.id)});return record}
  private async setState(client:PoolClient,workspaceId:string,pluginId:string,state:"enabled"|"disabled",revision:number,identityId:string,subjectId:string,now:string){const result=await client.query<PluginRow>(`UPDATE ${this.q("_xecms_plugins")} SET desired_state=$3,revision=revision+1,restart_required=true,updated_at=$4,updated_by=$5 WHERE workspace_id=$1 AND plugin_id=$2 AND revision=$6 RETURNING *`,[workspaceId,pluginId,state,now,identityId,revision]);const record=mapPlugin(result.rows[0]!);await this.audit(client,`plugin.${state}`,record,identityId,subjectId,now,{});return record}
  private async uninstall(client:PoolClient,workspaceId:string,module:XeCmsPluginModule,dataAction:PluginDataAction,identityId:string,subjectId:string,now:string){let exportId:string|undefined;if(dataAction==="export"){exportId=`plugin_export_${randomUUID()}`;const tables=module.manifest.dataTables??[],data=tables.length===0?"'{}'::jsonb":`jsonb_build_object(${tables.map((table,index)=>`$${7+index}::text,COALESCE((SELECT jsonb_agg(to_jsonb(plugin_row)) FROM ${this.q(table)} plugin_row),'[]'::jsonb)`).join(",")})`;await client.query(`INSERT INTO ${this.q("_xecms_plugin_exports")}(id,workspace_id,plugin_id,manifest,data,created_at,created_by) VALUES($1,$2,$3,$4::jsonb,${data},$5,$6)`,[exportId,workspaceId,module.manifest.id,JSON.stringify(module.manifest),now,identityId,...tables])}if(dataAction!=="preserve"){for(const migration of [...(module.server?.migrations??[])].reverse())await migration.down!(this.migrationContext(client));await client.query(`DELETE FROM ${this.q("_xecms_plugin_migrations")} WHERE workspace_id=$1 AND plugin_id=$2`,[workspaceId,module.manifest.id])}for(const permission of module.manifest.extensions?.permissions??[]){await client.query(`DELETE FROM ${this.q("_xecms_auth_role_permissions")} WHERE permission_key=$1`,[permission]);await client.query(`DELETE FROM ${this.q("_xecms_auth_permissions")} WHERE permission_key=$1`,[permission])}const current=await this.lockPlugin(client,workspaceId,module.manifest.id);await client.query(`DELETE FROM ${this.q("_xecms_plugins")} WHERE workspace_id=$1 AND plugin_id=$2`,[workspaceId,module.manifest.id]);await this.audit(client,"plugin.uninstalled",mapPlugin(current),identityId,subjectId,now,{dataAction,...(exportId?{exportId}:{})});return{exportId}}
  private async snapshot(client:PoolClient,workspaceId:string,module:XeCmsPluginModule,action:PluginPlanAction,dataAction:PluginDataAction|undefined,current:PluginRow|null){const blockers:PluginBlocker[]=[];const dependencyIds=Object.keys(module.manifest.dependencies??{}).sort();if(action==="install"&&current)blockers.push(block("PLUGIN_STATE","Plugin is already installed."));if(action!=="install"&&!current)blockers.push(block("PLUGIN_STATE","Plugin is not installed."));if(action==="enable"&&current&&!(current.desired_state==="installed"||current.desired_state==="disabled"))blockers.push(block("PLUGIN_STATE","Only installed or disabled Plugin can be enabled."));if(action==="disable"&&current?.desired_state!=="enabled")blockers.push(block("PLUGIN_STATE","Only enabled Plugin can be disabled."));if(action==="uninstall"&&current?.desired_state!=="disabled")blockers.push(block("PLUGIN_STATE","Plugin must be disabled before uninstall."));if(action==="uninstall"&&current?.desired_state==="disabled"&&current.restart_required)blockers.push(block("PLUGIN_STATE","Plugin disable must be reconciled by a server restart before uninstall."));if(action==="install"||action==="enable")for(const id of dependencyIds){const dep=await this.findPlugin(client,workspaceId,id,false);if(!dep||(action==="enable"&&dep.desired_state!=="enabled"))blockers.push(block("DEPENDENCY_MISSING",`Dependency '${id}' is not ready.`,{pluginId:id}))}if(action==="disable"||action==="uninstall"){const dependents=await client.query<{plugin_id:string}>(`SELECT plugin_id FROM ${this.q("_xecms_plugins")} WHERE workspace_id=$1 AND plugin_id<>$2 AND manifest->'dependencies' ? $2`,[workspaceId,module.manifest.id]);for(const row of dependents.rows)blockers.push(block("DEPENDENT_PLUGIN",`Plugin '${row.plugin_id}' depends on this Plugin.`,{pluginId:row.plugin_id}))}
    const schemaReferences:string[]=[];if((action==="disable"||action==="uninstall")&&(module.manifest.extensions?.fields?.length??0)>0){const schemas=await client.query<{source:"active"|"draft";schema_json:unknown}>(`SELECT 'active'::text source,revision.schema_json FROM ${this.q("_xecms_schema_state")} state JOIN ${this.q("_xecms_schema_revisions")} revision ON revision.revision_id=state.active_revision_id WHERE state.singleton=true UNION ALL SELECT 'draft'::text,draft.schema_json FROM ${this.q("_xecms_schema_drafts")} draft WHERE draft.workspace_id=$1`,[workspaceId]);for(const field of module.manifest.extensions?.fields??[])for(const row of schemas.rows)if(schemaUsesPluginField(row.schema_json,field.id))schemaReferences.push(`${row.source}:${field.id}`)}if(schemaReferences.length)blockers.push(block("SCHEMA_USAGE","Schema still references Plugin Field extensions.",{references:[...new Set(schemaReferences)]}));
    if(action==="uninstall")for(const permission of module.manifest.extensions?.permissions??[]){const usage=await client.query<{role_id:string}>(`SELECT role_permission.role_id FROM ${this.q("_xecms_auth_role_permissions")} role_permission JOIN ${this.q("_xecms_auth_roles")} role ON role.realm_id=role_permission.realm_id AND role.id=role_permission.role_id WHERE role_permission.permission_key=$1 AND role.id NOT IN ('authorization:'||role.realm_id||':role:owner','authorization:'||role.realm_id||':role:administrator')`,[permission]);if(usage.rowCount)blockers.push(block("PERMISSION_IN_USE",`Permission '${permission}' is assigned to a Role.`,{roleIds:usage.rows.map(x=>x.role_id)}))}
    const dataCounts:Record<string,number>={};for(const table of module.manifest.dataTables??[]){const exists=await client.query<{exists:boolean}>(`SELECT to_regclass($1) IS NOT NULL AS exists`,[`${this.schema}.${table}`]);dataCounts[table]=exists.rows[0]?.exists?Number((await client.query<{count:string}>(`SELECT count(*)::text count FROM ${this.q(table)}`)).rows[0]!.count):0}const hasData=Object.values(dataCounts).some(x=>x>0);if(action==="uninstall"&&hasData&&!dataAction)blockers.push(block("DATA_ACTION_REQUIRED","Plugin data exists; choose preserve, export or purge.",{dataCounts}));if(action==="uninstall"&&(dataAction==="export"||dataAction==="purge")&&(module.server?.migrations??[]).some(x=>!x.down))blockers.push(block("DOWN_MIGRATION_REQUIRED","Every migration requires down() for export or purge."));return{blockers,dependencyIds,schemaReferences,dataCounts,migrationIds:(module.manifest.migrations??[]).map(x=>x.id)}}
  private migrationContext(client:PoolClient):PluginMigrationContext{return{table:(name)=>this.q(name),query:async(sql,values=[])=>{const result=await client.query(sql,[...values]);return{rowCount:result.rowCount,rows:result.rows as Record<string,unknown>[]}}}}
  private async audit(client:PoolClient,eventType:string,record:PluginRecord,identityId:string,subjectId:string,now:string,metadata:Record<string,unknown>){const payload={workspaceId:record.workspaceId,pluginId:record.pluginId,revision:record.revision,actorSubjectId:subjectId,...metadata};const audit=await client.query<{id:string|number}>(`INSERT INTO ${this.q("_xecms_audit_log")}(event_type,identity_id,occurred_at,metadata) VALUES($1,$2,$3,$4::jsonb) RETURNING id`,[eventType,identityId,now,JSON.stringify(payload)]);await client.query(`INSERT INTO ${this.q("_xecms_outbox_events")}(id,workspace_id,realm_id,topic,aggregate_type,aggregate_id,aggregate_version,actor_subject_id,actor_identity_id,occurred_at,payload,created_at) VALUES($1,$2,$3,$4,'plugin',$5,$6,$7,$8,$9,$10::jsonb,$9)`,[`outbox_plugin_${audit.rows[0]!.id}`,record.workspaceId,SYSTEM_AUTHORIZATION_REALM_ID,eventType,record.pluginId,record.revision,subjectId,identityId,now,JSON.stringify(payload)])}
  private async findPlugin(client:PoolClient,workspaceId:string,pluginId:string,lock:boolean){const result=await client.query<PluginRow>(`SELECT * FROM ${this.q("_xecms_plugins")} WHERE workspace_id=$1 AND plugin_id=$2${lock?" FOR UPDATE":""}`,[workspaceId,pluginId]);return result.rows[0]??null}
  private async lockPlugin(client:PoolClient,workspaceId:string,pluginId:string){const row=await this.findPlugin(client,workspaceId,pluginId,true);if(!row)throw new ApplicationError("PLUGIN_NOT_INSTALLED",404,"Plugin is not installed.");return row}
  private assertExpected(current:PluginRow|null,expected:number|null){const actual=current?Number(current.revision):null;if(actual!==expected)throw new ApplicationError("PLUGIN_REVISION_CONFLICT",409,"Plugin changed after it was read.",{details:{expectedRevision:expected,actualRevision:actual}})}
  private q(name:string){return qualifiedName(this.schema,name)}
}

interface PluginRow extends QueryResultRow{workspace_id:string;plugin_id:string;package_name:string;version:string;manifest:XeCmsPluginManifestV1;manifest_digest:string;desired_state:"installed"|"enabled"|"disabled";config:Record<string,unknown>;revision:string|number;restart_required:boolean;installed_at:Date|string;installed_by:string;updated_at:Date|string;updated_by:string}
interface PlanRow extends QueryResultRow{id:string;workspace_id:string;plugin_id:string;action:PluginPlanAction;data_action:PluginDataAction|null;expected_plugin_revision:string|number|null;manifest_digest:string;status:"previewed"|"applied";blockers:PluginBlocker[];dependency_ids:string[];schema_references:string[];data_counts:Record<string,number>;migration_ids:string[];digest:string;created_at:Date|string;created_by:string;expires_at:Date|string;applied_at:Date|string|null;applied_by:string|null;result:PluginRecord|null;export_id:string|null}
function mapPlugin(row:PluginRow):PluginRecord{return{pluginId:row.plugin_id,workspaceId:row.workspace_id,packageName:row.package_name,version:row.version,manifest:row.manifest,manifestDigest:row.manifest_digest,desiredState:row.desired_state,config:row.config,revision:Number(row.revision),restartRequired:row.restart_required,installedAt:new Date(row.installed_at).toISOString(),installedBy:row.installed_by,updatedAt:new Date(row.updated_at).toISOString(),updatedBy:row.updated_by}}
function mapPlan(row:PlanRow):PluginPlan{return{id:row.id,workspaceId:row.workspace_id,pluginId:row.plugin_id,action:row.action,...(row.data_action?{dataAction:row.data_action}:{}),expectedPluginRevision:row.expected_plugin_revision===null?null:Number(row.expected_plugin_revision),manifestDigest:row.manifest_digest,status:row.status,blockers:row.blockers,dependencyIds:row.dependency_ids,schemaReferences:row.schema_references,dataCounts:row.data_counts,migrationIds:row.migration_ids,digest:row.digest,createdAt:new Date(row.created_at).toISOString(),createdBy:row.created_by,expiresAt:new Date(row.expires_at).toISOString(),...(row.applied_at?{appliedAt:new Date(row.applied_at).toISOString()}:{}),...(row.applied_by?{appliedBy:row.applied_by}:{}),...(row.status==="applied"?{result:row.result}:{}),...(row.export_id?{exportId:row.export_id}:{})}}
function block(code:PluginBlocker["code"],message:string,details?:Record<string,unknown>):PluginBlocker{return{code,message,...(details?{details}:{})}}
function schemaUsesPluginField(schema:unknown,fieldType:string):boolean{if(!record(schema))return false;const containers=[...(Array.isArray(schema["collections"])?schema["collections"]:[]),...(Array.isArray(schema["components"])?schema["components"]:[])];return containers.some(container=>record(container)&&fieldsUsePluginType(container["fields"],fieldType))}
function fieldsUsePluginType(fields:unknown,fieldType:string):boolean{return Array.isArray(fields)&&fields.some(field=>record(field)&&(field["type"]===fieldType||((field["type"]==="object"||field["type"]==="array")&&fieldsUsePluginType(field["fields"],fieldType))))}
function record(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
function planDigest(module:XeCmsPluginModule,action:PluginPlanAction,dataAction:PluginDataAction|undefined,revision:number|null,snapshot:{blockers:readonly PluginBlocker[];dependencyIds:readonly string[];schemaReferences:readonly string[];dataCounts:Readonly<Record<string,number>>;migrationIds:readonly string[]}){return pluginManifestDigest({...module.manifest,description:JSON.stringify({action,dataAction:dataAction??null,revision,snapshot})})}
