import { randomUUID } from "node:crypto";
import examplePlugin from "@xecms/example-plugin";
import { AuthorizationApplicationService,PluginCatalog,PluginService,SYSTEM_WORKSPACE_RESOURCE_ID } from "@xecms/application";
import { definePlugin } from "@xecms/plugin-sdk";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { qualifiedName,quoteIdentifier } from "./identifiers.js";
import { DEFAULT_WORKSPACE_ID,DEFAULT_WORKSPACE_NAME,SYSTEM_REALM_ID } from "./migrate.js";
import { applyPluginPlatformMigration,PLUGIN_PLATFORM_MIGRATION_ID } from "./plugin-migration.js";
import { PostgresAuthorizationStore } from "./postgres-authorization.js";
import { PostgresPluginStore } from "./postgres-plugins.js";
import { PostgresDatabase } from "./postgres.js";

const RUN=process.env["XECMS_RUN_POSTGRES_TESTS"]==="true";
const DATABASE_URL=process.env["XECMS_TEST_DATABASE_URL"]??process.env["DATABASE_URL"]??"postgresql://xecms:xecms@127.0.0.1:55432/xecms_e2e";
describe.runIf(RUN)("M4-C4 Plugin PostgreSQL lifecycle",()=>{
  const schema=`xecms_plugins_${randomUUID().replaceAll("-","_")}`,database=new PostgresDatabase({connectionString:DATABASE_URL,schema,maxConnections:4}),store=new PostgresPluginStore(database.pool,schema);
  const ownerId="usr_plugin_owner",now="2026-07-15T16:00:00.000Z";let sequence=0;
  const service=new PluginService(store,new PluginCatalog([examplePlugin]),{now:()=>now,newPlanId:()=>`plugin_plan_${++sequence}`,loadedPluginIds:new Set()});
  const q=(name:string)=>qualifiedName(schema,name);
  beforeAll(async()=>{await database.migrate();await database.createInitialOwner({id:ownerId,username:"plugin.owner",passwordHash:"hash",now});const authorization=new AuthorizationApplicationService(new PostgresAuthorizationStore(database.pool,schema),{now:()=>now,newAuditId:()=>`audit_${randomUUID()}`,newId:prefix=>`${prefix}_${randomUUID()}`});await authorization.initialize({realmId:SYSTEM_REALM_ID,realmName:"System Realm",rootResourceId:SYSTEM_WORKSPACE_RESOURCE_ID,rootResourceName:DEFAULT_WORKSPACE_NAME,ownerSubjectId:ownerId,ownerIdentityId:ownerId,ownerSubjectName:"plugin.owner"})});
  afterAll(async()=>{await database.pool.query(`DROP SCHEMA IF EXISTS ${quoteIdentifier(schema)} CASCADE`);await database.close()});
  it("installs migration 0018 idempotently",async()=>{expect((await database.pool.query(`SELECT 1 FROM ${q("_xecms_core_migrations")} WHERE id=$1`,[PLUGIN_PLATFORM_MIGRATION_ID])).rowCount).toBe(1);const client=await database.pool.connect();try{await client.query("BEGIN");await applyPluginPlatformMigration(client,schema);await client.query("COMMIT")}finally{client.release()}});
  it("installs, enables, reconciles restart, configures, disables and exports before uninstall",async()=>{
    const install=await service.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",action:"install",expectedPluginRevision:null,actorIdentityId:ownerId});expect(install.blockers).toEqual([]);
    const installed=await service.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:install.id,pluginId:"example-greeter",expectedPluginRevision:null,actorIdentityId:ownerId,actorSubjectId:ownerId});expect(installed.result).toMatchObject({desiredState:"installed",revision:1,restartRequired:true});expect((await database.pool.query(`SELECT message FROM ${q("_xecms_plugin_example_greeter_messages")}`)).rows).toEqual([{message:"Hello from Example Greeter"}]);
    const enable=await service.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",action:"enable",expectedPluginRevision:1,actorIdentityId:ownerId});const enabled=await service.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:enable.id,pluginId:"example-greeter",expectedPluginRevision:1,actorIdentityId:ownerId,actorSubjectId:ownerId});expect(enabled.result).toMatchObject({desiredState:"enabled",revision:2});
    const loadedService=new PluginService(store,new PluginCatalog([examplePlugin]),{now:()=>now,newPlanId:()=>`loaded_plan_${++sequence}`,loadedPluginIds:new Set(["example-greeter"])});await database.pool.query(`UPDATE ${q("_xecms_plugin_migrations")} SET checksum='drifted' WHERE plugin_id='example-greeter'`);await expect(loadedService.assertStartupState(DEFAULT_WORKSPACE_ID)).rejects.toMatchObject({code:"PLUGIN_MIGRATION_CHECKSUM_DRIFT"});await database.pool.query(`UPDATE ${q("_xecms_plugin_migrations")} SET checksum='sha256:example-greeter:0001:v1' WHERE plugin_id='example-greeter'`);await loadedService.assertStartupState(DEFAULT_WORKSPACE_ID);await loadedService.reconcileRuntime(DEFAULT_WORKSPACE_ID);expect(await loadedService.get(DEFAULT_WORKSPACE_ID,"example-greeter")).toMatchObject({restartRequired:false});
    const configured=await loadedService.updateConfig({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",expectedRevision:2,config:{greeting:"Hello configured"},actorIdentityId:ownerId,actorSubjectId:ownerId});expect(configured).toMatchObject({revision:3,restartRequired:true,config:{greeting:"Hello configured"}});
    const disable=await loadedService.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",action:"disable",expectedPluginRevision:3,actorIdentityId:ownerId});const disabled=await loadedService.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:disable.id,pluginId:"example-greeter",expectedPluginRevision:3,actorIdentityId:ownerId,actorSubjectId:ownerId});expect(disabled.result).toMatchObject({desiredState:"disabled",revision:4});
    const blocked=await loadedService.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",action:"uninstall",expectedPluginRevision:4,actorIdentityId:ownerId});expect(blocked.blockers).toEqual([expect.objectContaining({code:"PLUGIN_STATE"}),expect.objectContaining({code:"DATA_ACTION_REQUIRED"})]);await expect(loadedService.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:blocked.id,pluginId:"example-greeter",expectedPluginRevision:4,actorIdentityId:ownerId,actorSubjectId:ownerId})).rejects.toMatchObject({code:"PLUGIN_PLAN_BLOCKED"});
    const stoppedService=new PluginService(store,new PluginCatalog([examplePlugin]),{now:()=>now,newPlanId:()=>`stopped_plan_${++sequence}`,loadedPluginIds:new Set()});await stoppedService.assertStartupState(DEFAULT_WORKSPACE_ID);await stoppedService.reconcileRuntime(DEFAULT_WORKSPACE_ID);expect(await stoppedService.get(DEFAULT_WORKSPACE_ID,"example-greeter")).toMatchObject({restartRequired:false});
    const exportedPlan=await stoppedService.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"example-greeter",action:"uninstall",dataAction:"export",expectedPluginRevision:4,actorIdentityId:ownerId});expect(exportedPlan.blockers).toEqual([]);const removed=await stoppedService.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:exportedPlan.id,pluginId:"example-greeter",expectedPluginRevision:4,actorIdentityId:ownerId,actorSubjectId:ownerId});expect(removed).toMatchObject({status:"applied",result:null});expect(removed.exportId).toBeDefined();expect(await stoppedService.getExport(DEFAULT_WORKSPACE_ID,removed.exportId!)).toMatchObject({pluginId:"example-greeter",data:{_xecms_plugin_example_greeter_messages:[expect.objectContaining({id:"welcome"})]}});expect((await database.pool.query(`SELECT to_regclass($1) AS name`,[`${schema}._xecms_plugin_example_greeter_messages`])).rows[0]).toEqual({name:null});
    const audit=await database.pool.query(`SELECT event_type FROM ${q("_xecms_audit_log")} WHERE event_type LIKE 'plugin.%' ORDER BY id`);expect(audit.rows.map(row=>row.event_type)).toEqual(["plugin.installed","plugin.enabled","plugin.config.updated","plugin.disabled","plugin.uninstalled"]);
  });
  it("rolls back failed Plugin migration without installed or migration state",async()=>{const failing=definePlugin({manifest:{manifestVersion:1,id:"failing-plugin",packageName:"@test/failing-plugin",version:"1.0.0",displayName:"Failing",compatibility:{core:">=0.4.0 <0.5.0",admin:">=0.4.0 <0.5.0",sdk:"1.x"},serverEntry:"server",migrations:[{id:"0001_fail",checksum:"fail-v1"}],dataTables:["_xecms_plugin_failing_plugin_data"]},server:{migrations:[{id:"0001_fail",checksum:"fail-v1",up:async({query,table})=>{await query(`CREATE TABLE ${table("_xecms_plugin_failing_plugin_data")}(id text PRIMARY KEY)`);await query("THIS IS NOT SQL")},down:async({query,table})=>{await query(`DROP TABLE ${table("_xecms_plugin_failing_plugin_data")}`)}}]}});const failingService=new PluginService(store,new PluginCatalog([failing]),{now:()=>now,newPlanId:()=>"failing_plan",loadedPluginIds:new Set()});const plan=await failingService.preview({workspaceId:DEFAULT_WORKSPACE_ID,pluginId:"failing-plugin",action:"install",expectedPluginRevision:null,actorIdentityId:ownerId});await expect(failingService.apply({workspaceId:DEFAULT_WORKSPACE_ID,planId:plan.id,pluginId:"failing-plugin",expectedPluginRevision:null,actorIdentityId:ownerId,actorSubjectId:ownerId})).rejects.toBeDefined();expect(await store.get(DEFAULT_WORKSPACE_ID,"failing-plugin")).toBeNull();expect((await database.pool.query(`SELECT * FROM ${q("_xecms_plugin_migrations")} WHERE plugin_id='failing-plugin'`)).rowCount).toBe(0);expect((await database.pool.query(`SELECT to_regclass($1) AS name`,[`${schema}._xecms_plugin_failing_plugin_data`])).rows[0]).toEqual({name:null})});
});
